export const PRODUCTOS_LISTA = [

{	id:	"BZ-BO-001",	nombre:	"Bombillas halógenas",	categoria:	"Bazar y Varios",	subcategoria:	"Bombillas y material electrico",	formato:	"pack",	},
{	id:	"BZ-BO-002",	nombre:	"Bombillas LED bajo consumo",	categoria:	"Bazar y Varios",	subcategoria:	"Bombillas y material electrico",	formato:	"pack",	},
{	id:	"BZ-BO-003",	nombre:	"Regleta alargador",	categoria:	"Bazar y Varios",	subcategoria:	"Bombillas y material electrico",	formato:	"1ud",	},
{	id:	"BZ-ME-001",	nombre:	"Cazo pequeño",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-002",	nombre:	"Colador metálico",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-003",	nombre:	"Cucharas de mesa",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-004",	nombre:	"Cucharillas de postre",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-005",	nombre:	"Cucharón sopero",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-006",	nombre:	"Cuchillos de cocina",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-007",	nombre:	"Espátula de cocina silicona",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-008",	nombre:	"Fiambreras de cristal",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-009",	nombre:	"Fiambreras de plástico",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-010",	nombre:	"Juego de ollas de acero",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-011",	nombre:	"Platos de postre",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-012",	nombre:	"Platos hondos",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-013",	nombre:	"Platos llanos cerámica",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-014",	nombre:	"Sartenes antiadherentes",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-015",	nombre:	"Tabla de cortar",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-016",	nombre:	"Tapas de silicona reutilizables",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-017",	nombre:	"Tazas de desayuno",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"1ud",	},
{	id:	"BZ-ME-018",	nombre:	"Tenedores de mesa",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-ME-019",	nombre:	"Vasos de cristal",	categoria:	"Bazar y Varios",	subcategoria:	"Menaje y utensilios de cocina",	formato:	"pack",	},
{	id:	"BZ-OT-001",	nombre:	"Botellas reutilizables",	categoria:	"Bazar y Varios",	subcategoria:	"Otros bazar",	formato:	"1ud",	},
{	id:	"BZ-PA-001",	nombre:	"Archivadores de cartón",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"pack",	},
{	id:	"BZ-PA-002",	nombre:	"Bolígrafo azul",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"pack",	},
{	id:	"BZ-PA-003",	nombre:	"Bolígrafo negro",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"pack",	},
{	id:	"BZ-PA-004",	nombre:	"Carpetas de anillas",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-005",	nombre:	"Cinta adhesiva",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-006",	nombre:	"Cuadernos tamaño A4",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-007",	nombre:	"Cuadernos tamaño A5",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-008",	nombre:	"Goma de borrar",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-009",	nombre:	"Grapas para grapadora",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-010",	nombre:	"Hojas de impresora",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-011",	nombre:	"Lapiceros de grafito",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-012",	nombre:	"Rotuladores de colores",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-013",	nombre:	"Sacapuntas",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-014",	nombre:	"Sobres blancos",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PA-015",	nombre:	"Tijeras de oficina",	categoria:	"Bazar y Varios",	subcategoria:	"Papelería y oficina",	formato:	"1ud",	},
{	id:	"BZ-PI-001",	nombre:	"Pilas alcalinas AA",	categoria:	"Bazar y Varios",	subcategoria:	"Pilas",	formato:	"pack",	},
{	id:	"BZ-PI-002",	nombre:	"Pilas alcalinas AAA",	categoria:	"Bazar y Varios",	subcategoria:	"Pilas",	formato:	"pack",	},
{	id:	"BZ-PI-003",	nombre:	"Pilas botón",	categoria:	"Bazar y Varios",	subcategoria:	"Pilas",	formato:	"pack",	},
{	id:	"BZ-RE-001",	nombre:	"Revistas de actualidad",	categoria:	"Bazar y Varios",	subcategoria:	"Revistas",	formato:	"1ud",	},
{	id:	"BZ-RE-002",	nombre:	"Revistas de cocina",	categoria:	"Bazar y Varios",	subcategoria:	"Revistas",	formato:	"1ud",	},
{	id:	"BZ-RE-003",	nombre:	"Revistas de decoración",	categoria:	"Bazar y Varios",	subcategoria:	"Revistas",	formato:	"1ud",	},
{	id:	"BB-CO-001",	nombre:	"Agua mineral bebé",	categoria:	"Bebes",	subcategoria:	"Comida infantil",	formato:	"1ud",	},
{	id:	"BB-CO-002",	nombre:	"Cereales infantiles con miel",	categoria:	"Bebes",	subcategoria:	"Comida infantil",	formato:	"1ud",	},
{	id:	"BB-CO-003",	nombre:	"Cereales infantiles sin gluten",	categoria:	"Bebes",	subcategoria:	"Comida infantil",	formato:	"1ud",	},
{	id:	"BB-CO-004",	nombre:	"Galletitas para bebé",	categoria:	"Bebes",	subcategoria:	"Comida infantil",	formato:	"1ud",	},
{	id:	"BB-CO-005",	nombre:	"Potito de frutas variadas",	categoria:	"Bebes",	subcategoria:	"Comida infantil",	formato:	"1ud",	},
{	id:	"BB-CO-006",	nombre:	"Potito de verdura y merluza",	categoria:	"Bebes",	subcategoria:	"Comida infantil",	formato:	"1ud",	},
{	id:	"BB-CO-007",	nombre:	"Potito de verdura y pollo",	categoria:	"Bebes",	subcategoria:	"Comida infantil",	formato:	"1ud",	},
{	id:	"BB-CU-001",	nombre:	"Aceite corporal bebé",	categoria:	"Bebes",	subcategoria:	"Cuidado e higiene del bebé",	formato:	"1ud",	},
{	id:	"BB-CU-002",	nombre:	"Champú suave bebé",	categoria:	"Bebes",	subcategoria:	"Cuidado e higiene del bebé",	formato:	"1ud",	},
{	id:	"BB-CU-003",	nombre:	"Crema protectora pañal",	categoria:	"Bebes",	subcategoria:	"Cuidado e higiene del bebé",	formato:	"1ud",	},
{	id:	"BB-CU-004",	nombre:	"Gel de baño bebé",	categoria:	"Bebes",	subcategoria:	"Cuidado e higiene del bebé",	formato:	"1ud",	},
{	id:	"BB-LE-001",	nombre:	"Leche de fórmula continuación",	categoria:	"Bebes",	subcategoria:	"Leche de fórmula",	formato:	"1ud",	},
{	id:	"BB-LE-002",	nombre:	"Leche de fórmula inicio",	categoria:	"Bebes",	subcategoria:	"Leche de fórmula",	formato:	"1ud",	},
{	id:	"BB-PA-001",	nombre:	"Pañales talla 1",	categoria:	"Bebes",	subcategoria:	"Pañales",	formato:	"pack",	},
{	id:	"BB-PA-002",	nombre:	"Pañales talla 2",	categoria:	"Bebes",	subcategoria:	"Pañales",	formato:	"pack",	},
{	id:	"BB-PA-003",	nombre:	"Pañales talla 3",	categoria:	"Bebes",	subcategoria:	"Pañales",	formato:	"pack",	},
{	id:	"BB-PA-004",	nombre:	"Pañales talla 4",	categoria:	"Bebes",	subcategoria:	"Pañales",	formato:	"pack",	},
{	id:	"BB-PA-005",	nombre:	"Pañales talla 5",	categoria:	"Bebes",	subcategoria:	"Pañales",	formato:	"pack",	},
{	id:	"BB-TO-001",	nombre:	"Algodón hidrófilo bebé",	categoria:	"Bebes",	subcategoria:	"Toallitas y algodón",	formato:	"pack",	},
{	id:	"BB-TO-002",	nombre:	"Toallitas húmedas bebé",	categoria:	"Bebes",	subcategoria:	"Toallitas y algodón",	formato:	"pack",	},
{	id:	"BE-AG-001",	nombre:	"Agua mineral con gas",	categoria:	"Bebidas",	subcategoria:	"Agua",	formato:	"1,5l",	},
{	id:	"BE-AG-002",	nombre:	"Agua mineral natural",	categoria:	"Bebidas",	subcategoria:	"Agua",	formato:	"1,5l",	},
{	id:	"BE-CE-001",	nombre:	"Cerveza 0,0",	categoria:	"Bebidas",	subcategoria:	"Cerveza",	formato:	"0,33l",	},
{	id:	"BE-CE-002",	nombre:	"Cerveza rubia botella",	categoria:	"Bebidas",	subcategoria:	"Cerveza",	formato:	"1l",	},
{	id:	"BE-CE-003",	nombre:	"Cerveza rubia lata",	categoria:	"Bebidas",	subcategoria:	"Cerveza",	formato:	"0,33l",	},
{	id:	"BE-CE-004",	nombre:	"Cerveza sin gluten",	categoria:	"Bebidas",	subcategoria:	"Cerveza",	formato:	"0,33l",	},
{	id:	"BE-CE-005",	nombre:	"Cerveza tostada",	categoria:	"Bebidas",	subcategoria:	"Cerveza",	formato:	"0,33l",	},
{	id:	"BE-CE-006",	nombre:	"Sidra natural",	categoria:	"Bebidas",	subcategoria:	"Cerveza",	formato:	"1l",	},
{	id:	"BE-LI-001",	nombre:	"Ginebra estándar",	categoria:	"Bebidas",	subcategoria:	"Licores y destilados",	formato:	"500ml",	},
{	id:	"BE-LI-002",	nombre:	"Licor de café",	categoria:	"Bebidas",	subcategoria:	"Licores y destilados",	formato:	"500ml",	},
{	id:	"BE-LI-003",	nombre:	"Licor de hierbas",	categoria:	"Bebidas",	subcategoria:	"Licores y destilados",	formato:	"500ml",	},
{	id:	"BE-LI-004",	nombre:	"Ron añejo",	categoria:	"Bebidas",	subcategoria:	"Licores y destilados",	formato:	"500ml",	},
{	id:	"BE-LI-005",	nombre:	"Ron blanco",	categoria:	"Bebidas",	subcategoria:	"Licores y destilados",	formato:	"500ml",	},
{	id:	"BE-LI-006",	nombre:	"Vodka",	categoria:	"Bebidas",	subcategoria:	"Licores y destilados",	formato:	"500ml",	},
{	id:	"BE-LI-007",	nombre:	"Whisky blended",	categoria:	"Bebidas",	subcategoria:	"Licores y destilados",	formato:	"500ml",	},
{	id:	"BE-RE-001",	nombre:	"Agua saborizada limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-RE-002",	nombre:	"Bebida isotónica limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-RE-003",	nombre:	"Refresco de cola",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-RE-004",	nombre:	"Refresco de cola sin azúcar",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-RE-005",	nombre:	"Refresco de lima-limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-RE-006",	nombre:	"Refresco de limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-RE-007",	nombre:	"Refresco de naranja",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-RE-008",	nombre:	"Agua saborizada limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-009",	nombre:	"Bebida isotónica limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-010",	nombre:	"Refresco de cola",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-011",	nombre:	"Refresco de cola sin azúcar",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-012",	nombre:	"Refresco de lima-limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-013",	nombre:	"Refresco de limón",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-014",	nombre:	"Refresco de naranja",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-015",	nombre:	"Refresco de naranja zero",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"2l",	},
{	id:	"BE-RE-016",	nombre:	"Tónica",	categoria:	"Bebidas",	subcategoria:	"Refrescos",	formato:	"0,33l",	},
{	id:	"BE-VI-001",	nombre:	"Vermut blanco",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-002",	nombre:	"Vermut rojo",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-003",	nombre:	"Vino blanco afrutado",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-004",	nombre:	"Vino blanco seco",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-005",	nombre:	"Vino espumoso brut",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-006",	nombre:	"Vino espumoso cava",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-007",	nombre:	"Vino rosado",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-008",	nombre:	"Vino tinto crianza",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-VI-009",	nombre:	"Vino tinto joven",	categoria:	"Bebidas",	subcategoria:	"Vino",	formato:	"750ml",	},
{	id:	"BE-ZU-001",	nombre:	"Néctar de melocotón",	categoria:	"Bebidas",	subcategoria:	"Zumos",	formato:	"1,5l",	},
{	id:	"BE-ZU-002",	nombre:	"Zumo de naranja envasado",	categoria:	"Bebidas",	subcategoria:	"Zumos",	formato:	"1,5l",	},
{	id:	"BE-ZU-003",	nombre:	"Zumo de piña",	categoria:	"Bebidas",	subcategoria:	"Zumos",	formato:	"1,5l",	},
{	id:	"BE-ZU-004",	nombre:	"Zumo de tomate",	categoria:	"Bebidas",	subcategoria:	"Zumos",	formato:	"1,5l",	},
{	id:	"BE-ZU-005",	nombre:	"Zumo multifrutas",	categoria:	"Bebidas",	subcategoria:	"Zumos",	formato:	"1,5l",	},
{	id:	"CA-CA-001",	nombre:	"Albóndigas preparadas",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-002",	nombre:	"Carne picada mixta",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-003",	nombre:	"Hamburguesas de vacuno",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-004",	nombre:	"Hamburguesas mixtas",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-005",	nombre:	"Pinchos morunos de cerdo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-006",	nombre:	"Pinchos morunos de pollo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-007",	nombre:	"Redondo de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-008",	nombre:	"Salchichas de pavo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-009",	nombre:	"Salchichas de pollo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-010",	nombre:	"Salchichas frescas para parrilla",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"1kg",	},
{	id:	"CA-CA-011",	nombre:	"Salchichas tipo Frankfurt",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"pack",	},
{	id:	"CA-CA-012",	nombre:	"Salchichas tipo Viena",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Carne preparada",	formato:	"pack",	},
{	id:	"CA-CE-001",	nombre:	"Bacon loncheado",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-002",	nombre:	"Carne de cerdo para guiso",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-003",	nombre:	"Carrilleras de cerdo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-004",	nombre:	"Chuletas de lomo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-005",	nombre:	"Costillas de cerdo adobadas",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-006",	nombre:	"Lomo de cerdo en filetes",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-007",	nombre:	"Lomo de cerdo entero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-008",	nombre:	"Paleta ibérica",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-009",	nombre:	"Panceta curada",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-010",	nombre:	"Panceta fresca",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-011",	nombre:	"Pluma ibérica",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-012",	nombre:	"Secreto ibérico",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-013",	nombre:	"Solomillo de cerdo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CE-014",	nombre:	"Tacos de bacon",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cerdo",	formato:	"1kg",	},
{	id:	"CA-CH-001",	nombre:	"Cecina de vaca",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-002",	nombre:	"Chorizo dulce",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-003",	nombre:	"Chorizo fresco para guisar",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-004",	nombre:	"Chorizo picante",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-005",	nombre:	"Embutido de pollo bajo en grasa",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-006",	nombre:	"Fuet",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-007",	nombre:	"Jamón cocido en lonchas",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-008",	nombre:	"Jamón en taquitos para cocinar",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-009",	nombre:	"Jamón ibérico loncheado",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-010",	nombre:	"Jamón serrano en pieza",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-011",	nombre:	"Jamón serrano loncheado",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-012",	nombre:	"Jamón york bajo en sal",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-013",	nombre:	"Lomo embuchado",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-014",	nombre:	"Longaniza",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-015",	nombre:	"Mortadela",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-016",	nombre:	"Mortadela con aceitunas",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-017",	nombre:	"Salami",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-018",	nombre:	"Salchichón cular",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CH-019",	nombre:	"Salchichón extra loncheado",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Charcuteria",	formato:	"1kg",	},
{	id:	"CA-CO-001",	nombre:	"Chuletas de cordero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cordero",	formato:	"1kg",	},
{	id:	"CA-CO-002",	nombre:	"Cordero lechal entero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cordero",	formato:	"1kg",	},
{	id:	"CA-CO-003",	nombre:	"Paletilla de cordero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cordero",	formato:	"1kg",	},
{	id:	"CA-CO-004",	nombre:	"Pierna de cordero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cordero",	formato:	"1kg",	},
{	id:	"CA-CO-005",	nombre:	"Riñones de cordero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Cordero",	formato:	"1kg",	},
{	id:	"CA-PA-001",	nombre:	"Alas de pavo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pavo",	formato:	"1kg",	},
{	id:	"CA-PA-002",	nombre:	"Fiambre de pavo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pavo",	formato:	"1kg",	},
{	id:	"CA-PA-003",	nombre:	"Muslos de pavo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pavo",	formato:	"1kg",	},
{	id:	"CA-PA-004",	nombre:	"Pavo troceado",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pavo",	formato:	"1kg",	},
{	id:	"CA-PA-005",	nombre:	"Pechuga de pavo braseada",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pavo",	formato:	"1kg",	},
{	id:	"CA-PO-001",	nombre:	"Alitas de pollo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-002",	nombre:	"Brochetas de pollo adobadas",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-003",	nombre:	"Carne picada de pollo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-004",	nombre:	"Contramuslos de pollo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-005",	nombre:	"Hígado de pollo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-006",	nombre:	"Muslos de pollo",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-007",	nombre:	"Pechuga de pollo marinada",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-008",	nombre:	"Pechugas de pollo frescas",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-009",	nombre:	"Pollo campero entero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-PO-010",	nombre:	"Pollo entero",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Pollo",	formato:	"1kg",	},
{	id:	"CA-VA-001",	nombre:	"Callos de vacuno",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-002",	nombre:	"Carne de res para estofado",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-003",	nombre:	"Carne de res para guiso",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-004",	nombre:	"Carne picada de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-005",	nombre:	"Chuletas de aguja",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-006",	nombre:	"Chuletón de vaca",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-007",	nombre:	"Costillas adobadas barbacoa",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-008",	nombre:	"Costillas de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-009",	nombre:	"Entrecot de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-010",	nombre:	"Falda de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-011",	nombre:	"Filetes de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-012",	nombre:	"Hígado de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-013",	nombre:	"Rabo de toro",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CA-VA-014",	nombre:	"Solomillo de ternera",	categoria:	"Carnicería y Charcutería",	subcategoria:	"Vacuno",	formato:	"1kg",	},
{	id:	"CO-HE-001",	nombre:	"Bombones helados",	categoria:	"Congelados",	subcategoria:	"Helados y postres congelados",	formato:	"pack",	},
{	id:	"CO-HE-002",	nombre:	"Helado de chocolate",	categoria:	"Congelados",	subcategoria:	"Helados y postres congelados",	formato:	"pack",	},
{	id:	"CO-HE-003",	nombre:	"Helado de fresa",	categoria:	"Congelados",	subcategoria:	"Helados y postres congelados",	formato:	"pack",	},
{	id:	"CO-HE-004",	nombre:	"Helado de nata y nueces",	categoria:	"Congelados",	subcategoria:	"Helados y postres congelados",	formato:	"pack",	},
{	id:	"CO-HE-005",	nombre:	"Helado de vainilla",	categoria:	"Congelados",	subcategoria:	"Helados y postres congelados",	formato:	"pack",	},
{	id:	"CO-HE-006",	nombre:	"Polos de hielo sabores surtidos",	categoria:	"Congelados",	subcategoria:	"Helados y postres congelados",	formato:	"pack",	},
{	id:	"CO-HE-007",	nombre:	"Tarta helada de nata y chocolate",	categoria:	"Congelados",	subcategoria:	"Helados y postres congelados",	formato:	"1ud",	},
{	id:	"CO-PL-001",	nombre:	"Albóndigas de carne congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-002",	nombre:	"Anillas de calamar rebozadas congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-003",	nombre:	"Canelones de carne congelados",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-004",	nombre:	"Croquetas de jamón congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-005",	nombre:	"Croquetas de pollo congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-006",	nombre:	"Fideuá congelada",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-007",	nombre:	"Filetes de merluza rebozados congelados",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-008",	nombre:	"Fingers de pollo congelados",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-009",	nombre:	"Hamburguesas de pollo congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-010",	nombre:	"Hamburguesas de vacuno congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-011",	nombre:	"Lasaña de carne congelada",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-012",	nombre:	"Lasaña de espinacas congelada",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-013",	nombre:	"Nuggets de pollo congelados",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-014",	nombre:	"Paella mixta congelada",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-015",	nombre:	"Patatas fritas congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-016",	nombre:	"Pizza congelada barbacoa",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-017",	nombre:	"Pizza congelada cuatro quesos",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-018",	nombre:	"Pizza congelada jamón y queso",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-PL-019",	nombre:	"Varitas de pescado congeladas",	categoria:	"Congelados",	subcategoria:	"Platos congelados preparados",	formato:	"1kg",	},
{	id:	"CO-VG-001",	nombre:	"Espinacas congeladas en porciones",	categoria:	"Congelados",	subcategoria:	"Verduras congeladas",	formato:	"1kg",	},
{	id:	"CO-VG-002",	nombre:	"Guisantes congelados",	categoria:	"Congelados",	subcategoria:	"Verduras congeladas",	formato:	"1kg",	},
{	id:	"CO-VG-003",	nombre:	"Judías verdes congeladas",	categoria:	"Congelados",	subcategoria:	"Verduras congeladas",	formato:	"1kg",	},
{	id:	"CO-VG-004",	nombre:	"Mezcla de verduras para ensaladilla",	categoria:	"Congelados",	subcategoria:	"Verduras congeladas",	formato:	"1kg",	},
{	id:	"CO-VG-005",	nombre:	"Pimientos troceados congelados",	categoria:	"Congelados",	subcategoria:	"Verduras congeladas",	formato:	"1kg",	},
{	id:	"CO-VG-006",	nombre:	"Salteado de verduras congelado",	categoria:	"Congelados",	subcategoria:	"Verduras congeladas",	formato:	"1kg",	},
{	id:	"CO-VG-007",	nombre:	"Verduras para sopa congeladas",	categoria:	"Congelados",	subcategoria:	"Verduras congeladas",	formato:	"1kg",	},
{	id:	"CO-CM-001",	nombre:	"Almejas en conserva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de marisco/moluscos especificos",	formato:	"1ud",	},
{	id:	"CO-CM-002",	nombre:	"Berberechos en conserva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de marisco/moluscos especificos",	formato:	"1ud",	},
{	id:	"CO-CO-001",	nombre:	"Anchoas en aceite de oliva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-002",	nombre:	"Atún al natural",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-003",	nombre:	"Atún en aceite de girasol",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-004",	nombre:	"Atún en aceite de oliva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-005",	nombre:	"Bonito del norte en aceite",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-006",	nombre:	"Caballa en aceite de oliva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-007",	nombre:	"Chipirones en su tinta",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-008",	nombre:	"Mejillones en escabeche",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-009",	nombre:	"Pulpo en aceite",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-010",	nombre:	"Sardinas en aceite de oliva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-CO-011",	nombre:	"Sardinas en escabeche",	categoria:	"Conservas y Enlatados",	subcategoria:	"Conservas de pescado y mariscos",	formato:	"1ud",	},
{	id:	"CO-FR-001",	nombre:	"Cóctel de frutas en almíbar",	categoria:	"Conservas y Enlatados",	subcategoria:	"Frutas en almibar o en su jugo",	formato:	"1ud",	},
{	id:	"CO-FR-002",	nombre:	"Frutas en almíbar (melocotón)",	categoria:	"Conservas y Enlatados",	subcategoria:	"Frutas en almibar o en su jugo",	formato:	"1ud",	},
{	id:	"CO-FR-003",	nombre:	"Peras en almíbar",	categoria:	"Conservas y Enlatados",	subcategoria:	"Frutas en almibar o en su jugo",	formato:	"1ud",	},
{	id:	"CO-FR-004",	nombre:	"Piña en su jugo",	categoria:	"Conservas y Enlatados",	subcategoria:	"Frutas en almibar o en su jugo",	formato:	"1ud",	},
{	id:	"CO-SO-001",	nombre:	"Crema de verduras en lata",	categoria:	"Conservas y Enlatados",	subcategoria:	"Sopas, cremas y otros preparados",	formato:	"1ud",	},
{	id:	"CO-SO-002",	nombre:	"Puré de patata instantáneo en caja",	categoria:	"Conservas y Enlatados",	subcategoria:	"Sopas, cremas y otros preparados",	formato:	"1ud",	},
{	id:	"CO-SO-003",	nombre:	"Sopa de cocido en lata",	categoria:	"Conservas y Enlatados",	subcategoria:	"Sopas, cremas y otros preparados",	formato:	"1ud",	},
{	id:	"CO-VE-001",	nombre:	"Alcachofas en conserva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-002",	nombre:	"Alubias blancas cocidas",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-003",	nombre:	"Alubias rojas cocidas",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-004",	nombre:	"Garbanzos cocidos en tarro",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-005",	nombre:	"Guisantes en conserva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-006",	nombre:	"Judías verdes en conserva",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-007",	nombre:	"Lentejas cocidas en tarro",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-008",	nombre:	"Maíz dulce en lata",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-009",	nombre:	"Pimientos del piquillo en tarro",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-010",	nombre:	"Tomate entero pelado en lata",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CO-VE-011",	nombre:	"Tomate triturado en lata",	categoria:	"Conservas y Enlatados",	subcategoria:	"Verduras, legumbres y hortalizas en conserva",	formato:	"1ud",	},
{	id:	"CP-CR-001",	nombre:	"Crema de manos",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cremas y protectores",	formato:	"1ud",	},
{	id:	"CP-CR-002",	nombre:	"Crema hidratante corporal",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cremas y protectores",	formato:	"1ud",	},
{	id:	"CP-CR-003",	nombre:	"Crema hidratante facial",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cremas y protectores",	formato:	"1ud",	},
{	id:	"CP-CR-004",	nombre:	"Protector solar corporal",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cremas y protectores",	formato:	"1ud",	},
{	id:	"CP-CR-005",	nombre:	"Protector solar facial",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cremas y protectores",	formato:	"1ud",	},
{	id:	"CP-CC-001",	nombre:	"Acondicionador capilar",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cuidado del cabello",	formato:	"1ud",	},
{	id:	"CP-CC-002",	nombre:	"Champú anticaspa",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cuidado del cabello",	formato:	"1ud",	},
{	id:	"CP-CC-003",	nombre:	"Champú cabello graso",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cuidado del cabello",	formato:	"1ud",	},
{	id:	"CP-CC-004",	nombre:	"Champú cabello normal",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cuidado del cabello",	formato:	"1ud",	},
{	id:	"CP-CC-005",	nombre:	"Mascarilla para el pelo",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Cuidado del cabello",	formato:	"1ud",	},
{	id:	"CP-DE-001",	nombre:	"Desodorante de pies",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Desodorantes",	formato:	"1ud",	},
{	id:	"CP-DE-002",	nombre:	"Desodorante en roll-on",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Desodorantes",	formato:	"1ud",	},
{	id:	"CP-DE-003",	nombre:	"Desodorante en spray",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Desodorantes",	formato:	"1ud",	},
{	id:	"CP-HB-001",	nombre:	"Cepillo de dientes eléctrico",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene bucal",	formato:	"1ud",	},
{	id:	"CP-HB-002",	nombre:	"Cepillo de dientes manual",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene bucal",	formato:	"1ud",	},
{	id:	"CP-HB-003",	nombre:	"Colutorio bucal",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene bucal",	formato:	"1ud",	},
{	id:	"CP-HB-004",	nombre:	"Hilo dental",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene bucal",	formato:	"1ud",	},
{	id:	"CP-HB-005",	nombre:	"Pasta de dientes blanqueadora",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene bucal",	formato:	"1ud",	},
{	id:	"CP-HB-006",	nombre:	"Pasta de dientes con flúor",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene bucal",	formato:	"1ud",	},
{	id:	"CP-HC-001",	nombre:	"Gel de baño",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene corporal",	formato:	"1ud",	},
{	id:	"CP-HC-002",	nombre:	"Gel íntimo",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene corporal",	formato:	"1ud",	},
{	id:	"CP-HC-003",	nombre:	"Jabón de manos en pastilla",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene corporal",	formato:	"1ud",	},
{	id:	"CP-HC-004",	nombre:	"Jabón de manos líquido",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene corporal",	formato:	"1ud",	},
{	id:	"CP-HC-005",	nombre:	"Jabón íntimo masculino",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene corporal",	formato:	"1ud",	},
{	id:	"CP-HI-001",	nombre:	"Bastoncillos de algodón",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene intima femenina y accesorios",	formato:	"pack",	},
{	id:	"CP-HI-002",	nombre:	"Compresas",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene intima femenina y accesorios",	formato:	"pack",	},
{	id:	"CP-HI-003",	nombre:	"Discos desmaquillantes",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene intima femenina y accesorios",	formato:	"pack",	},
{	id:	"CP-HI-004",	nombre:	"Salvaslips",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene intima femenina y accesorios",	formato:	"pack",	},
{	id:	"CP-HI-005",	nombre:	"Tampones",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene intima femenina y accesorios",	formato:	"pack",	},
{	id:	"CP-HI-006",	nombre:	"Toallitas desmaquillantes",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Higiene intima femenina y accesorios",	formato:	"pack",	},
{	id:	"CP-PR-001",	nombre:	"After shave loción",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Productos de afeitado",	formato:	"pack",	},
{	id:	"CP-PR-002",	nombre:	"Cuchillas de afeitar desechables",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Productos de afeitado",	formato:	"pack",	},
{	id:	"CP-PR-003",	nombre:	"Espuma de afeitar",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Productos de afeitado",	formato:	"1ud",	},
{	id:	"CP-PR-004",	nombre:	"Máquina de afeitar recargable",	categoria:	"Cuidado personal e Higiene",	subcategoria:	"Productos de afeitado",	formato:	"1ud",	},
{	id:	"DE-CA-001",	nombre:	"Cacao en polvo soluble",	categoria:	"Desayuno y Snack",	subcategoria:	"Café y cacaos",	formato:	"750g",	},
{	id:	"DE-CA-002",	nombre:	"Café en grano",	categoria:	"Desayuno y Snack",	subcategoria:	"Café y cacaos",	formato:	"1ud",	},
{	id:	"DE-CA-003",	nombre:	"Café molido mezcla",	categoria:	"Desayuno y Snack",	subcategoria:	"Café y cacaos",	formato:	"1ud",	},
{	id:	"DE-CA-004",	nombre:	"Café molido natural",	categoria:	"Desayuno y Snack",	subcategoria:	"Café y cacaos",	formato:	"1ud",	},
{	id:	"DE-CA-005",	nombre:	"Café soluble",	categoria:	"Desayuno y Snack",	subcategoria:	"Café y cacaos",	formato:	"1ud",	},
{	id:	"DE-CA-006",	nombre:	"Cápsulas de café compatibles",	categoria:	"Desayuno y Snack",	subcategoria:	"Café y cacaos",	formato:	"pack",	},
{	id:	"DE-CA-007",	nombre:	"Descafeinado soluble",	categoria:	"Desayuno y Snack",	subcategoria:	"Café y cacaos",	formato:	"1ud",	},
{	id:	"DE-CE-001",	nombre:	"Avena en copos",	categoria:	"Desayuno y Snack",	subcategoria:	"Cereales para desayuno",	formato:	"1ud",	},
{	id:	"DE-CE-002",	nombre:	"Barritas de cereales",	categoria:	"Desayuno y Snack",	subcategoria:	"Cereales para desayuno",	formato:	"1ud",	},
{	id:	"DE-CE-003",	nombre:	"Cereales de chocolate",	categoria:	"Desayuno y Snack",	subcategoria:	"Cereales para desayuno",	formato:	"1ud",	},
{	id:	"DE-CE-004",	nombre:	"Cereales de maíz simples",	categoria:	"Desayuno y Snack",	subcategoria:	"Cereales para desayuno",	formato:	"1ud",	},
{	id:	"DE-CE-005",	nombre:	"Cereales integrales tipo muesli",	categoria:	"Desayuno y Snack",	subcategoria:	"Cereales para desayuno",	formato:	"1ud",	},
{	id:	"DE-CE-006",	nombre:	"Tostadas crujientes de trigo",	categoria:	"Desayuno y Snack",	subcategoria:	"Cereales para desayuno",	formato:	"1ud",	},
{	id:	"DE-CR-001",	nombre:	"Crema de cacahuete",	categoria:	"Desayuno y Snack",	subcategoria:	"Cremas",	formato:	"1ud",	},
{	id:	"DE-CR-002",	nombre:	"Crema de cacao y avellanas",	categoria:	"Desayuno y Snack",	subcategoria:	"Cremas",	formato:	"1ud",	},
{	id:	"DE-FR-001",	nombre:	"Frutos secos envasados almendras",	categoria:	"Desayuno y Snack",	subcategoria:	"Frutos secos embasados",	formato:	"150g",	},
{	id:	"DE-FR-002",	nombre:	"Mix frutos secos con pasas",	categoria:	"Desayuno y Snack",	subcategoria:	"Frutos secos embasados",	formato:	"150g",	},
{	id:	"DE-GA-001",	nombre:	"Galletas de avena",	categoria:	"Desayuno y Snack",	subcategoria:	"Galletas dulces",	formato:	"pack",	},
{	id:	"DE-GA-002",	nombre:	"Galletas digestive",	categoria:	"Desayuno y Snack",	subcategoria:	"Galletas dulces",	formato:	"pack",	},
{	id:	"DE-GA-003",	nombre:	"Galletas maría",	categoria:	"Desayuno y Snack",	subcategoria:	"Galletas dulces",	formato:	"pack",	},
{	id:	"DE-GA-004",	nombre:	"Galletas rellenas de chocolate",	categoria:	"Desayuno y Snack",	subcategoria:	"Galletas dulces",	formato:	"pack",	},
{	id:	"DE-GS-001",	nombre:	"Galletas saladas tipo cracker",	categoria:	"Desayuno y Snack",	subcategoria:	"Galletas saladas",	formato:	"pack",	},
{	id:	"DE-ME-001",	nombre:	"Mermelada de fresa",	categoria:	"Desayuno y Snack",	subcategoria:	"Mermelada y Miel",	formato:	"1ud",	},
{	id:	"DE-ME-002",	nombre:	"Mermelada de melocotón",	categoria:	"Desayuno y Snack",	subcategoria:	"Mermelada y Miel",	formato:	"1ud",	},
{	id:	"DE-ME-003",	nombre:	"Mermelada de naranja amarga",	categoria:	"Desayuno y Snack",	subcategoria:	"Mermelada y Miel",	formato:	"1ud",	},
{	id:	"DE-ME-004",	nombre:	"Miel de azahar",	categoria:	"Desayuno y Snack",	subcategoria:	"Mermelada y Miel",	formato:	"1ud",	},
{	id:	"DE-ME-005",	nombre:	"Miel de flores",	categoria:	"Desayuno y Snack",	subcategoria:	"Mermelada y Miel",	formato:	"1ud",	},
{	id:	"DE-SN-001",	nombre:	"Barritas energéticas de frutos secos",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-SN-002",	nombre:	"Nachos de maíz",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-SN-003",	nombre:	"Palitos salados",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-SN-004",	nombre:	"Palomitas para microondas mantequilla",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-SN-005",	nombre:	"Palomitas para microondas sal",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-SN-006",	nombre:	"Patatas fritas clásicas",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-SN-007",	nombre:	"Patatas fritas sabor jamón",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-SN-008",	nombre:	"Patatas fritas sabor queso",	categoria:	"Desayuno y Snack",	subcategoria:	"Snack salados",	formato:	"pack",	},
{	id:	"DE-TE-001",	nombre:	"Infusión de manzanilla",	categoria:	"Desayuno y Snack",	subcategoria:	"Té e infusiones",	formato:	"pack",	},
{	id:	"DE-TE-002",	nombre:	"Infusión de menta poleo",	categoria:	"Desayuno y Snack",	subcategoria:	"Té e infusiones",	formato:	"pack",	},
{	id:	"DE-TE-003",	nombre:	"Té negro en bolsitas",	categoria:	"Desayuno y Snack",	subcategoria:	"Té e infusiones",	formato:	"pack",	},
{	id:	"DE-TE-004",	nombre:	"Té verde en bolsitas",	categoria:	"Desayuno y Snack",	subcategoria:	"Té e infusiones",	formato:	"pack",	},
{	id:	"DS-AC-001",	nombre:	"Aceite de girasol",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"1l",	},
{	id:	"DS-AC-002",	nombre:	"Aceite de oliva suave",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"1l",	},
{	id:	"DS-AC-003",	nombre:	"Aceite de oliva virgen extra",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"1l",	},
{	id:	"DS-AC-004",	nombre:	"Aceite de girasol",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"3l",	},
{	id:	"DS-AC-005",	nombre:	"Aceite de oliva suave",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"3l",	},
{	id:	"DS-AC-006",	nombre:	"Aceite de oliva virgen extra",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"3l",	},
{	id:	"DS-AC-007",	nombre:	"Aceite de girasol",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"5l",	},
{	id:	"DS-AC-008",	nombre:	"Aceite de oliva suave",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"5l",	},
{	id:	"DS-AC-009",	nombre:	"Aceite de oliva virgen extra",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"5l",	},
{	id:	"DS-AC-010",	nombre:	"Aceite de semillas",	categoria:	"Despensa",	subcategoria:	"Aceites",	formato:	"1l",	},
{	id:	"DS-AR-001",	nombre:	"Arroz basmati",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-002",	nombre:	"Arroz integral",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-003",	nombre:	"Arroz largo",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-004",	nombre:	"Arroz redondo",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-005",	nombre:	"Couscous medio",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-006",	nombre:	"Pasta espaguetis",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-007",	nombre:	"Pasta macarrones",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-008",	nombre:	"Pasta para sopa (fideos)",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-009",	nombre:	"Pasta plumas integrales",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AR-010",	nombre:	"Quinoa",	categoria:	"Despensa",	subcategoria:	"Arroz, pasta y quinoa",	formato:	"1kg",	},
{	id:	"DS-AZ-001",	nombre:	"Azúcar blanco",	categoria:	"Despensa",	subcategoria:	"Azúcares y edulcorantes",	formato:	"1kg",	},
{	id:	"DS-AZ-002",	nombre:	"Azúcar glas",	categoria:	"Despensa",	subcategoria:	"Azúcares y edulcorantes",	formato:	"1kg",	},
{	id:	"DS-AZ-003",	nombre:	"Azúcar moreno",	categoria:	"Despensa",	subcategoria:	"Azúcares y edulcorantes",	formato:	"1kg",	},
{	id:	"DS-AZ-004",	nombre:	"Edulcorante en sobres",	categoria:	"Despensa",	subcategoria:	"Azúcares y edulcorantes",	formato:	"pack",	},
{	id:	"DS-ES-001",	nombre:	"Albahaca seca",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-002",	nombre:	"Canela en rama",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-003",	nombre:	"Canela molida",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-004",	nombre:	"Comino molido",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-005",	nombre:	"Curry en polvo",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-006",	nombre:	"Mezcla de especias para carne",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-007",	nombre:	"Mezcla de especias para paella",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-008",	nombre:	"Nuez moscada molida",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-009",	nombre:	"Orégano seco",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-010",	nombre:	"Pimentón dulce",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-011",	nombre:	"Pimentón picante",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-012",	nombre:	"Pimienta blanca",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-013",	nombre:	"Pimienta negra molida",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-014",	nombre:	"Romero seco",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-ES-015",	nombre:	"Tomillo seco",	categoria:	"Despensa",	subcategoria:	"Especias e hierbas secas",	formato:	"1ud",	},
{	id:	"DS-HA-001",	nombre:	"Harina de maíz",	categoria:	"Despensa",	subcategoria:	"Harinas",	formato:	"1kg",	},
{	id:	"DS-HA-002",	nombre:	"Harina de repostería",	categoria:	"Despensa",	subcategoria:	"Harinas",	formato:	"1kg",	},
{	id:	"DS-HA-003",	nombre:	"Harina de trigo",	categoria:	"Despensa",	subcategoria:	"Harinas",	formato:	"1kg",	},
{	id:	"DS-HA-004",	nombre:	"Harina integral",	categoria:	"Despensa",	subcategoria:	"Harinas",	formato:	"1kg",	},
{	id:	"DS-LE-001",	nombre:	"Alubias blancas secas",	categoria:	"Despensa",	subcategoria:	"Legumbres secas",	formato:	"1kg",	},
{	id:	"DS-LE-002",	nombre:	"Alubias pintas secas",	categoria:	"Despensa",	subcategoria:	"Legumbres secas",	formato:	"1kg",	},
{	id:	"DS-LE-003",	nombre:	"Garbanzos secos",	categoria:	"Despensa",	subcategoria:	"Legumbres secas",	formato:	"1kg",	},
{	id:	"DS-LE-004",	nombre:	"Lentejas pardinas secas",	categoria:	"Despensa",	subcategoria:	"Legumbres secas",	formato:	"1kg",	},
{	id:	"DS-LE-005",	nombre:	"Lentejas rojas secas",	categoria:	"Despensa",	subcategoria:	"Legumbres secas",	formato:	"1kg",	},
{	id:	"DS-SA-001",	nombre:	"Sal fina",	categoria:	"Despensa",	subcategoria:	"Sales",	formato:	"1kg",	},
{	id:	"DS-SA-002",	nombre:	"Sal gruesa",	categoria:	"Despensa",	subcategoria:	"Sales",	formato:	"1kg",	},
{	id:	"DS-SA-003",	nombre:	"Sal marina",	categoria:	"Despensa",	subcategoria:	"Sales",	formato:	"1kg",	},
{	id:	"DS-SC-001",	nombre:	"Alioli en tarro",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-002",	nombre:	"Caldo de carne en brik",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"pack 12ud",	},
{	id:	"DS-SC-003",	nombre:	"Caldo de pollo en brik",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"pack 12ud",	},
{	id:	"DS-SC-004",	nombre:	"Caldo de verduras en brik",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"pack 12ud",	},
{	id:	"DS-SC-005",	nombre:	"Caldos concentrados en pastilla",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"pack 12ud",	},
{	id:	"DS-SC-006",	nombre:	"Mayonesa en tarro",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-007",	nombre:	"Mostaza clásica",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-008",	nombre:	"Mostaza de Dijon",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-009",	nombre:	"Salsa barbacoa",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-010",	nombre:	"Salsa boloñesa en bote",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-011",	nombre:	"Salsa carbonara en bote",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-012",	nombre:	"Salsa cesar",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-013",	nombre:	"Salsa de soja",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-014",	nombre:	"Salsa de tomate frito",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-015",	nombre:	"Salsa ketchup",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-016",	nombre:	"Salsa pesto verde",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1ud",	},
{	id:	"DS-SC-017",	nombre:	"Tomate natural troceado",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1kg",	},
{	id:	"DS-SC-018",	nombre:	"Tomate triturado en brik",	categoria:	"Despensa",	subcategoria:	"Salsas, caldos y condimentos preparados",	formato:	"1kg",	},
{	id:	"DS-VI-001",	nombre:	"Vinagre balsámico",	categoria:	"Despensa",	subcategoria:	"Vinagres",	formato:	"1l",	},
{	id:	"DS-VI-002",	nombre:	"Vinagre de manzana",	categoria:	"Despensa",	subcategoria:	"Vinagres",	formato:	"1l",	},
{	id:	"DS-VI-003",	nombre:	"Vinagre de vino blanco",	categoria:	"Despensa",	subcategoria:	"Vinagres",	formato:	"1l",	},
{	id:	"DS-VI-004",	nombre:	"Vinagre de Módena",	categoria:	"Despensa",	subcategoria:	"Vinagres",	formato:	"1l",	},
{	id:	"DS-VI-005",	nombre:	"Vinagre de vino tinto",	categoria:	"Despensa",	subcategoria:	"Vinagres",	formato:	"1l",	},
{	id:	"FR-FR-001",	nombre:	"Aguacates",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-002",	nombre:	"Albaricoques",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-003",	nombre:	"Anacardos",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-004",	nombre:	"Arándanos",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-005",	nombre:	"Arándanos deshidratados",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-006",	nombre:	"Ciruelas amarillas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-007",	nombre:	"Ciruelas deshidratadas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-008",	nombre:	"Ciruelas rojas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-009",	nombre:	"Cocos enteros",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-010",	nombre:	"Frambuesas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-011",	nombre:	"Fresas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-012",	nombre:	"Granadas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-013",	nombre:	"Higos frescos",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-014",	nombre:	"Kiwis amarillos",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-015",	nombre:	"Kiwis verdes",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-016",	nombre:	"Limones",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-017",	nombre:	"Mandarinas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-018",	nombre:	"Mango",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-019",	nombre:	"Manzanas rojas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-020",	nombre:	"Manzanas verdes",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-021",	nombre:	"Melocotones",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-022",	nombre:	"Melón piel de sapo",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-023",	nombre:	"Moras",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-024",	nombre:	"Naranjas de mesa",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-025",	nombre:	"Naranjas para zumo",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-026",	nombre:	"Nectarinas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-027",	nombre:	"Papaya",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-028",	nombre:	"Pasas sultanas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-029",	nombre:	"Peras conferencia",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-030",	nombre:	"Piña natural",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-031",	nombre:	"Plátanos de Canarias",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-032",	nombre:	"Pomelos",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-033",	nombre:	"Sandía rayada",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-034",	nombre:	"Shiitake fresco",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-035",	nombre:	"Uvas blancas",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FR-036",	nombre:	"Uvas negras",	categoria:	"Frutas y Verduras",	subcategoria:	"Fruta",	formato:	"1kg",	},
{	id:	"FR-FS-001",	nombre:	"Avellanas",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-FS-002",	nombre:	"Castañas frescas",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-FS-003",	nombre:	"Frutos secos a granel: almendras crudas",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-FS-004",	nombre:	"Mezcla de frutos secos crudos",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-FS-005",	nombre:	"Mezcla de frutos secos tostados",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-FS-006",	nombre:	"Nueces",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-FS-007",	nombre:	"Cebolla frita",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-FS-008",	nombre:	"Pistachos",	categoria:	"Frutas y Verduras",	subcategoria:	"Frutos secos",	formato:	"150g",	},
{	id:	"FR-SE-001",	nombre:	"Champiñones enteros",	categoria:	"Frutas y Verduras",	subcategoria:	"Setas",	formato:	"250g",	},
{	id:	"FR-SE-002",	nombre:	"Champiñones laminados",	categoria:	"Frutas y Verduras",	subcategoria:	"Setas",	formato:	"250g",	},
{	id:	"FR-SE-003",	nombre:	"Setas variadas",	categoria:	"Frutas y Verduras",	subcategoria:	"Setas",	formato:	"250g",	},
{	id:	"FR-VE-001",	nombre:	"Acelgas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-002",	nombre:	"Ajos cabeza",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-003",	nombre:	"Ajos pelados",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-004",	nombre:	"Albahaca fresca",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-005",	nombre:	"Almendras tostadas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-006",	nombre:	"Apio",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-007",	nombre:	"Berenjenas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-008",	nombre:	"Brócoli",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-009",	nombre:	"Brotes variados",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-010",	nombre:	"Calabacines",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-011",	nombre:	"Calabaza entera",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-012",	nombre:	"Calabaza troceada",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-013",	nombre:	"Cebollas blancas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-014",	nombre:	"Cebollas dulces",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-015",	nombre:	"Cebollas rojas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-016",	nombre:	"Cebollino fresco",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-017",	nombre:	"Cilantro fresco",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-018",	nombre:	"Col blanca",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-019",	nombre:	"Col lombarda",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-020",	nombre:	"Col rizada (kale)",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-021",	nombre:	"Coliflor",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-022",	nombre:	"Eneldo fresco",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-023",	nombre:	"Espinacas frescas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-024",	nombre:	"Hierbabuena fresca",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-025",	nombre:	"Judías verdes planas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-026",	nombre:	"Judías verdes redondas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-027",	nombre:	"Lechuga hoja de roble",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-028",	nombre:	"Lechuga iceberg",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-029",	nombre:	"Lechuga romana",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-030",	nombre:	"Maíz dulce en mazorca",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-031",	nombre:	"Nabo",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-032",	nombre:	"Patatas blancas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"malla 3kg",	},
{	id:	"FR-VE-033",	nombre:	"Patatas nuevas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"malla 3kg",	},
{	id:	"FR-VE-034",	nombre:	"Patatas para freír",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"malla 3kg",	},
{	id:	"FR-VE-035",	nombre:	"Patatas blancas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"malla 5kg",	},
{	id:	"FR-VE-036",	nombre:	"Patatas nuevas",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"malla 5kg",	},
{	id:	"FR-VE-037",	nombre:	"Patatas para freír",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"malla 5kg",	},
{	id:	"FR-VE-038",	nombre:	"Pepinos español",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-039",	nombre:	"Pepinos holandés",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-040",	nombre:	"Perejil fresco",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-041",	nombre:	"Pimientos amarillos",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-042",	nombre:	"Pimientos del padrón",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-043",	nombre:	"Pimientos italianos",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-044",	nombre:	"Pimientos rojos",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-045",	nombre:	"Pimientos verdes",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-046",	nombre:	"Puerros",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-047",	nombre:	"Rábanos",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-048",	nombre:	"Remolacha fresca",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-049",	nombre:	"Romero fresco",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-050",	nombre:	"Salvia fresca",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-051",	nombre:	"Tomate cherry",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-052",	nombre:	"Tomate pera",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-053",	nombre:	"Tomate rama",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-054",	nombre:	"Tomates de ensalada",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-055",	nombre:	"Tomillo fresco",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"FR-VE-056",	nombre:	"Zanahorias",	categoria:	"Frutas y Verduras",	subcategoria:	"Verduras",	formato:	"1kg",	},
{	id:	"HO-AM-001",	nombre:	"Ambientador eléctrico recambio",	categoria:	"Hogar",	subcategoria:	"Ambientadores",	formato:	"1ud",	},
{	id:	"HO-AM-002",	nombre:	"Ambientador en aerosol",	categoria:	"Hogar",	subcategoria:	"Ambientadores",	formato:	"1ud",	},
{	id:	"HO-BO-001",	nombre:	"Bolsas de basura 30L",	categoria:	"Hogar",	subcategoria:	"Bolsas de basura y congelacion",	formato:	"1ud",	},
{	id:	"HO-BO-002",	nombre:	"Bolsas de basura 50L",	categoria:	"Hogar",	subcategoria:	"Bolsas de basura y congelacion",	formato:	"1ud",	},
{	id:	"HO-BO-003",	nombre:	"Bolsas de congelación con cierre",	categoria:	"Hogar",	subcategoria:	"Bolsas de basura y congelacion",	formato:	"1ud",	},
{	id:	"HO-DE-001",	nombre:	"Detergente en cápsulas",	categoria:	"Hogar",	subcategoria:	"Detergentes para ropa",	formato:	"1ud",	},
{	id:	"HO-DE-002",	nombre:	"Detergente en polvo",	categoria:	"Hogar",	subcategoria:	"Detergentes para ropa",	formato:	"1ud",	},
{	id:	"HO-DE-003",	nombre:	"Detergente líquido para lavadora",	categoria:	"Hogar",	subcategoria:	"Detergentes para ropa",	formato:	"1ud",	},
{	id:	"HO-DE-004",	nombre:	"Jabón para prendas delicadas",	categoria:	"Hogar",	subcategoria:	"Detergentes para ropa",	formato:	"1ud",	},
{	id:	"HO-DE-005",	nombre:	"Quitamanchas en spray",	categoria:	"Hogar",	subcategoria:	"Detergentes para ropa",	formato:	"1ud",	},
{	id:	"HO-LA-001",	nombre:	"Abrillantador lavavajillas",	categoria:	"Hogar",	subcategoria:	"Lavavajillas",	formato:	"1ud",	},
{	id:	"HO-LA-002",	nombre:	"Lavavajillas manual limón",	categoria:	"Hogar",	subcategoria:	"Lavavajillas",	formato:	"1ud",	},
{	id:	"HO-LA-003",	nombre:	"Lavavajillas máquina en pastillas",	categoria:	"Hogar",	subcategoria:	"Lavavajillas",	formato:	"1ud",	},
{	id:	"HO-LA-004",	nombre:	"Sal para lavavajillas",	categoria:	"Hogar",	subcategoria:	"Lavavajillas",	formato:	"1ud",	},
{	id:	"HO-LE-001",	nombre:	"Desinfectante multiusos",	categoria:	"Hogar",	subcategoria:	"Lejia y desinfectantes",	formato:	"1ud",	},
{	id:	"HO-LE-002",	nombre:	"Lejía con detergente",	categoria:	"Hogar",	subcategoria:	"Lejia y desinfectantes",	formato:	"1ud",	},
{	id:	"HO-LE-003",	nombre:	"Lejía concentrada",	categoria:	"Hogar",	subcategoria:	"Lejia y desinfectantes",	formato:	"1ud",	},
{	id:	"HO-LI-001",	nombre:	"Limpiacristales en spray",	categoria:	"Hogar",	subcategoria:	"Limpiadores de superficie",	formato:	"1ud",	},
{	id:	"HO-LI-002",	nombre:	"Limpiador amoniacal",	categoria:	"Hogar",	subcategoria:	"Limpiadores de superficie",	formato:	"1ud",	},
{	id:	"HO-LI-003",	nombre:	"Limpiador de baño antical",	categoria:	"Hogar",	subcategoria:	"Limpiadores de superficie",	formato:	"1ud",	},
{	id:	"HO-LI-004",	nombre:	"Limpiador de cocina desengrasante",	categoria:	"Hogar",	subcategoria:	"Limpiadores de superficie",	formato:	"1ud",	},
{	id:	"HO-LI-005",	nombre:	"Limpiador de suelos fregasuelos",	categoria:	"Hogar",	subcategoria:	"Limpiadores de superficie",	formato:	"1ud",	},
{	id:	"HO-LI-006",	nombre:	"Limpiador multiusos",	categoria:	"Hogar",	subcategoria:	"Limpiadores de superficie",	formato:	"1ud",	},
{	id:	"HO-SU-001",	nombre:	"Suavizante ropa floral",	categoria:	"Hogar",	subcategoria:	"Suavizantes",	formato:	"1ud",	},
{	id:	"HO-SU-002",	nombre:	"Suavizante ropa hipoalergénico",	categoria:	"Hogar",	subcategoria:	"Suavizantes",	formato:	"1ud",	},
{	id:	"HO-UT-001",	nombre:	"Bayetas multiusos",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"pack",	},
{	id:	"HO-UT-002",	nombre:	"Estropajos fuertes",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"pack",	},
{	id:	"HO-UT-003",	nombre:	"Estropajos suaves",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"pack",	},
{	id:	"HO-UT-004",	nombre:	"Guantes de limpieza de látex",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"pack",	},
{	id:	"HO-UT-005",	nombre:	"Paños de microfibra",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"pack",	},
{	id:	"HO-UT-006",	nombre:	"Papel aluminio",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"1ud",	},
{	id:	"HO-UT-007",	nombre:	"Papel de cocina rollo",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"1ud",	},
{	id:	"HO-UT-008",	nombre:	"Papel film transparente",	categoria:	"Hogar",	subcategoria:	"Utensilios y consumibles de limpieza",	formato:	"1ud",	},
{	id:	"LA-GR-001",	nombre:	"Margarina vegetal",	categoria:	"Lácteos y Huevos",	subcategoria:	"Grasas vegetales",	formato:	"250g",	},
{	id:	"LA-HU-001",	nombre:	"Claras de huevo pasteurizadas",	categoria:	"Lácteos y Huevos",	subcategoria:	"Huevos",	formato:	"1l",	},
{	id:	"LA-HU-002",	nombre:	"Huevos camperos",	categoria:	"Lácteos y Huevos",	subcategoria:	"Huevos",	formato:	"12ud",	},
{	id:	"LA-HU-003",	nombre:	"Huevos talla XL docena",	categoria:	"Lácteos y Huevos",	subcategoria:	"Huevos",	formato:	"12ud",	},
{	id:	"LA-HU-004",	nombre:	"Huevos talla L docena",	categoria:	"Lácteos y Huevos",	subcategoria:	"Huevos",	formato:	"12ud",	},
{	id:	"LA-HU-005",	nombre:	"Huevos talla M docena",	categoria:	"Lácteos y Huevos",	subcategoria:	"Huevos",	formato:	"12ud",	},
{	id:	"LA-LE-001",	nombre:	"Leche de almendras",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-002",	nombre:	"Leche de arroz",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-003",	nombre:	"Leche de avena",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-004",	nombre:	"Leche de soja",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-005",	nombre:	"Leche desnatada brik",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-006",	nombre:	"Leche entera brik",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-007",	nombre:	"Leche semidesnatada brik",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-008",	nombre:	"Leche desnatada botella",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1,5l",	},
{	id:	"LA-LE-009",	nombre:	"Leche entera botella",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1,5l",	},
{	id:	"LA-LE-010",	nombre:	"Leche semidesnatada botella",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1,5l",	},
{	id:	"LA-LE-011",	nombre:	"Leche sin lactosa entera",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-LE-012",	nombre:	"Leche sin lactosa semi",	categoria:	"Lácteos y Huevos",	subcategoria:	"Leche y bebidas lácteas",	formato:	"1l",	},
{	id:	"LA-MA-001",	nombre:	"Crema de leche espesa",	categoria:	"Lácteos y Huevos",	subcategoria:	"Mantequillas y Natas",	formato:	"1ud",	},
{	id:	"LA-MA-002",	nombre:	"Mantequilla con sal",	categoria:	"Lácteos y Huevos",	subcategoria:	"Mantequillas y Natas",	formato:	"1ud",	},
{	id:	"LA-MA-003",	nombre:	"Mantequilla sin sal",	categoria:	"Lácteos y Huevos",	subcategoria:	"Mantequillas y Natas",	formato:	"1ud",	},
{	id:	"LA-MA-004",	nombre:	"Nata para cocinar",	categoria:	"Lácteos y Huevos",	subcategoria:	"Mantequillas y Natas",	formato:	"1ud",	},
{	id:	"LA-MA-005",	nombre:	"Nata para montar",	categoria:	"Lácteos y Huevos",	subcategoria:	"Mantequillas y Natas",	formato:	"1ud",	},
{	id:	"LA-PO-001",	nombre:	"Flan de huevo",	categoria:	"Lácteos y Huevos",	subcategoria:	"Postres lácteos",	formato:	"pack",	},
{	id:	"LA-PO-002",	nombre:	"Flan de vainilla",	categoria:	"Lácteos y Huevos",	subcategoria:	"Postres lácteos",	formato:	"pack",	},
{	id:	"LA-PO-003",	nombre:	"Natillas de vainilla",	categoria:	"Lácteos y Huevos",	subcategoria:	"Postres lácteos",	formato:	"pack",	},
{	id:	"LA-PO-004",	nombre:	"Postres lácteos de chocolate",	categoria:	"Lácteos y Huevos",	subcategoria:	"Postres lácteos",	formato:	"pack",	},
{	id:	"LA-QU-001",	nombre:	"Queso azul",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1kg",	},
{	id:	"LA-QU-002",	nombre:	"Queso brie",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1kg",	},
{	id:	"LA-QU-003",	nombre:	"Queso camembert",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1kg",	},
{	id:	"LA-QU-004",	nombre:	"Queso cheddar en lonchas",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1ud",	},
{	id:	"LA-QU-005",	nombre:	"Queso de cabra rulo",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1kg",	},
{	id:	"LA-QU-006",	nombre:	"Queso en lonchas para sándwich",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"pack",	},
{	id:	"LA-QU-007",	nombre:	"Queso fresco batido",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1ud",	},
{	id:	"LA-QU-008",	nombre:	"Queso fresco de burgos",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"pack",	},
{	id:	"LA-QU-009",	nombre:	"Queso manchego curado",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1kg",	},
{	id:	"LA-QU-010",	nombre:	"Queso manchego semicurado",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1kg",	},
{	id:	"LA-QU-011",	nombre:	"Queso rallado mezcla",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1ud",	},
{	id:	"LA-QU-012",	nombre:	"Queso rallado mozzarella",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1ud",	},
{	id:	"LA-QU-013",	nombre:	"Queso rallado para gratinar",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1ud",	},
{	id:	"LA-QU-014",	nombre:	"Requesón",	categoria:	"Lácteos y Huevos",	subcategoria:	"Quesos",	formato:	"1ud",	},
{	id:	"LA-YO-001",	nombre:	"Yogur de sabores surtidos",	categoria:	"Lácteos y Huevos",	subcategoria:	"Yogures",	formato:	"pack",	},
{	id:	"LA-YO-002",	nombre:	"Yogur griego azucarado",	categoria:	"Lácteos y Huevos",	subcategoria:	"Yogures",	formato:	"pack",	},
{	id:	"LA-YO-003",	nombre:	"Yogur griego natural",	categoria:	"Lácteos y Huevos",	subcategoria:	"Yogures",	formato:	"pack",	},
{	id:	"LA-YO-004",	nombre:	"Yogur líquido bebible",	categoria:	"Lácteos y Huevos",	subcategoria:	"Yogures",	formato:	"pack",	},
{	id:	"LA-YO-005",	nombre:	"Yogur natural azucarado",	categoria:	"Lácteos y Huevos",	subcategoria:	"Yogures",	formato:	"pack",	},
{	id:	"LA-YO-006",	nombre:	"Yogur natural sin azúcar",	categoria:	"Lácteos y Huevos",	subcategoria:	"Yogures",	formato:	"pack",	},
{	id:	"MA-AR-001",	nombre:	"Arena aglomerante para gatos",	categoria:	"Mascotas",	subcategoria:	"Arena y asea para gatos",	formato:	"1ud",	},
{	id:	"MA-AR-002",	nombre:	"Arena de sílice para gatos",	categoria:	"Mascotas",	subcategoria:	"Arena y asea para gatos",	formato:	"1ud",	},
{	id:	"MA-AR-003",	nombre:	"Bandeja higiénica para gatos",	categoria:	"Mascotas",	subcategoria:	"Arena y asea para gatos",	formato:	"1ud",	},
{	id:	"MA-CG-001",	nombre:	"Comida húmeda para gato sobres",	categoria:	"Mascotas",	subcategoria:	"Comida para gatos",	formato:	"1kg",	},
{	id:	"MA-CG-002",	nombre:	"Pienso seco para gato adulto",	categoria:	"Mascotas",	subcategoria:	"Comida para gatos",	formato:	"1kg",	},
{	id:	"MA-CG-003",	nombre:	"Pienso seco para gato cachorro",	categoria:	"Mascotas",	subcategoria:	"Comida para gatos",	formato:	"1kg",	},
{	id:	"MA-CG-004",	nombre:	"Pienso seco para gato esterilizado",	categoria:	"Mascotas",	subcategoria:	"Comida para gatos",	formato:	"1kg",	},
{	id:	"MA-CP-001",	nombre:	"Comida húmeda para perro lata",	categoria:	"Mascotas",	subcategoria:	"Comida para perros",	formato:	"1kg",	},
{	id:	"MA-CP-002",	nombre:	"Huesos masticables perro",	categoria:	"Mascotas",	subcategoria:	"Comida para perros",	formato:	"1kg",	},
{	id:	"MA-CP-003",	nombre:	"Pienso seco para perro adulto",	categoria:	"Mascotas",	subcategoria:	"Comida para perros",	formato:	"1kg",	},
{	id:	"MA-CP-004",	nombre:	"Pienso seco para perro cachorro",	categoria:	"Mascotas",	subcategoria:	"Comida para perros",	formato:	"1kg",	},
{	id:	"MA-CP-005",	nombre:	"Pienso seco para perro senior",	categoria:	"Mascotas",	subcategoria:	"Comida para perros",	formato:	"1kg",	},
{	id:	"MA-CP-006",	nombre:	"Snacks dentales para perro",	categoria:	"Mascotas",	subcategoria:	"Comida para perros",	formato:	"1kg",	},
{	id:	"MA-JU-001",	nombre:	"Juguete con plumas para gatos",	categoria:	"Mascotas",	subcategoria:	"Juguetes y accesorios",	formato:	"1ud",	},
{	id:	"MA-JU-002",	nombre:	"Juguete de cuerda para perro",	categoria:	"Mascotas",	subcategoria:	"Juguetes y accesorios",	formato:	"1ud",	},
{	id:	"MA-JU-003",	nombre:	"Pelota de goma para perro",	categoria:	"Mascotas",	subcategoria:	"Juguetes y accesorios",	formato:	"1ud",	},
{	id:	"MA-JU-004",	nombre:	"Rascador para gatos",	categoria:	"Mascotas",	subcategoria:	"Juguetes y accesorios",	formato:	"1ud",	},
{	id:	"PA-BO-001",	nombre:	"Bollos de leche",	categoria:	"Panadería y Pastelería",	subcategoria:	"Bollos",	formato:	"1kg",	},
{	id:	"PA-BO-002",	nombre:	"Churros para freír",	categoria:	"Panadería y Pastelería",	subcategoria:	"Bollos",	formato:	"1kg",	},
{	id:	"PA-BO-003",	nombre:	"Croissants mantequilla",	categoria:	"Panadería y Pastelería",	subcategoria:	"Bollos",	formato:	"1kg",	},
{	id:	"PA-BO-004",	nombre:	"Croissants rellenos de chocolate",	categoria:	"Panadería y Pastelería",	subcategoria:	"Bollos",	formato:	"1kg",	},
{	id:	"PA-BO-005",	nombre:	"Ensaimadas",	categoria:	"Panadería y Pastelería",	subcategoria:	"Bollos",	formato:	"1kg",	},
{	id:	"PA-BO-006",	nombre:	"Magdalenas clásicas",	categoria:	"Panadería y Pastelería",	subcategoria:	"Bollos",	formato:	"1kg",	},
{	id:	"PA-BO-007",	nombre:	"Magdalenas integrales",	categoria:	"Panadería y Pastelería",	subcategoria:	"Bollos",	formato:	"1kg",	},
{	id:	"PA-PA-001",	nombre:	"Bases de pizza frescas",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PA-002",	nombre:	"Pan baguette",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"1ud",	},
{	id:	"PA-PA-003",	nombre:	"Pan barra artesana",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"1ud",	},
{	id:	"PA-PA-004",	nombre:	"Pan de bocadillo integral",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"1ud",	},
{	id:	"PA-PA-005",	nombre:	"Pan de hamburguesa",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PA-006",	nombre:	"Pan de molde blanco",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PA-007",	nombre:	"Pan de molde sin corteza",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PA-008",	nombre:	"Pan de perrito caliente",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PA-009",	nombre:	"Pan de pueblo",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"1ud",	},
{	id:	"PA-PA-010",	nombre:	"Pan integral de molde",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PA-011",	nombre:	"Picos de pan",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PA-012",	nombre:	"Regañás",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pan fresco",	formato:	"pack",	},
{	id:	"PA-PT-001",	nombre:	"Tarta de manzana",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pasteles y Tartas",	formato:	"1ud",	},
{	id:	"PA-PT-002",	nombre:	"Tarta de queso",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pasteles y Tartas",	formato:	"1ud",	},
{	id:	"PA-PT-003",	nombre:	"Tarta de tres chocolates",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pasteles y Tartas",	formato:	"1ud",	},
{	id:	"PA-PT-004",	nombre:	"Tarta de zanahoria",	categoria:	"Panadería y Pastelería",	subcategoria:	"Pasteles y Tartas",	formato:	"1ud",	},
{	id:	"PA-RE-001",	nombre:	"Bizcocho de limón",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"1ud",	},
{	id:	"PA-RE-002",	nombre:	"Bizcocho de yogur",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"1ud",	},
{	id:	"PA-RE-003",	nombre:	"Bizcocho marmolado",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"1ud",	},
{	id:	"PA-RE-004",	nombre:	"Colines integrales",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-005",	nombre:	"Donuts de chocolate",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-006",	nombre:	"Donuts glaseados",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-007",	nombre:	"Galletas de hojaldre",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-008",	nombre:	"Hojaldres rellenos de crema",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-009",	nombre:	"Masa de hojaldre fresca",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-010",	nombre:	"Napolitanas de chocolate",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-011",	nombre:	"Napolitanas de crema",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-012",	nombre:	"Palmeras de hojaldre",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-013",	nombre:	"Pastelitos surtidos",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PA-RE-014",	nombre:	"Rosquillas fritas",	categoria:	"Panadería y Pastelería",	subcategoria:	"Reposteria",	formato:	"pack",	},
{	id:	"PE-MA-001",	nombre:	"Bogavante",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-002",	nombre:	"Buey de mar",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-003",	nombre:	"Cangrejo de mar",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-004",	nombre:	"Cigalas",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-005",	nombre:	"Gambas frescas",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-006",	nombre:	"Gambón argentino",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-007",	nombre:	"Langostinos cocidos",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-008",	nombre:	"Langostinos crudos",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-009",	nombre:	"Ostras",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MA-010",	nombre:	"Palitos de cangrejo refrigerados",	categoria:	"Pescadería",	subcategoria:	"Marisco",	formato:	"1kg",	},
{	id:	"PE-MO-001",	nombre:	"Almejas finas",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-002",	nombre:	"Anillas de calamar",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-003",	nombre:	"Berberechos",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-004",	nombre:	"Calamares enteros",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-005",	nombre:	"Chipirones limpios",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-006",	nombre:	"Mejillones frescos",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-007",	nombre:	"Navajas",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-008",	nombre:	"Ostras",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-009",	nombre:	"Pulpo congelado descongelado",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-MO-010",	nombre:	"Sepia limpia",	categoria:	"Pescadería",	subcategoria:	"Moluscos",	formato:	"1kg",	},
{	id:	"PE-PE-001",	nombre:	"Anchoas frescas",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-002",	nombre:	"Atún fresco",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-003",	nombre:	"Bacalao fresco",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-004",	nombre:	"Bonito del norte",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-005",	nombre:	"Boquerones frescos",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-006",	nombre:	"Caballa fresca",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-007",	nombre:	"Dorada entera",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-008",	nombre:	"Jureles",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-009",	nombre:	"Lenguado",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-010",	nombre:	"Lubina entera",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-011",	nombre:	"Merluza fresca en lomos",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-012",	nombre:	"Merluza fresca en rodajas",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-013",	nombre:	"Rape en trozos",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-014",	nombre:	"Rodaballo por porciones",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-015",	nombre:	"Salmón fresco en lomos",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-016",	nombre:	"Salmón fresco en rodajas",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-017",	nombre:	"Salmonete",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PE-PE-018",	nombre:	"Sardinas frescas",	categoria:	"Pescadería",	subcategoria:	"Pescado",	formato:	"1kg",	},
{	id:	"PP-BO-001",	nombre:	"Sándwich mixto envasado",	categoria:	"Platos preparados",	subcategoria:	"Bocadillos y Sándwich listos",	formato:	"1ud",	},
{	id:	"PP-BO-002",	nombre:	"Sándwich vegetal",	categoria:	"Platos preparados",	subcategoria:	"Bocadillos y Sándwich listos",	formato:	"1ud",	},
{	id:	"PP-EN-001",	nombre:	"Ensalada César lista para comer",	categoria:	"Platos preparados",	subcategoria:	"Ensaladas listas",	formato:	"1ud",	},
{	id:	"PP-EN-002",	nombre:	"Ensalada de col (coleslaw)",	categoria:	"Platos preparados",	subcategoria:	"Ensaladas listas",	formato:	"1ud",	},
{	id:	"PP-EN-003",	nombre:	"Ensalada de pasta preparada",	categoria:	"Platos preparados",	subcategoria:	"Ensaladas listas",	formato:	"1ud",	},
{	id:	"PP-EN-004",	nombre:	"Ensaladilla rusa",	categoria:	"Platos preparados",	subcategoria:	"Ensaladas listas",	formato:	"1ud",	},
{	id:	"PP-PC-001",	nombre:	"Albóndigas en salsa preparadas",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-002",	nombre:	"Callos preparados",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-003",	nombre:	"Canelones de carne frescos",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-004",	nombre:	"Costillas BBQ preparadas",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-005",	nombre:	"Croquetas de jamón preparadas",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-006",	nombre:	"Croquetas de pollo preparadas",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-007",	nombre:	"Empanada de carne",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-008",	nombre:	"Medio pollo asado",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-009",	nombre:	"Pollo asado entero",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PC-010",	nombre:	"Wraps de pollo",	categoria:	"Platos preparados",	subcategoria:	"Platos de carne / ave",	formato:	"racion",	},
{	id:	"PP-PA-001",	nombre:	"Fideuá preparada",	categoria:	"Platos preparados",	subcategoria:	"Platos de pasta / arroz / fideos",	formato:	"racion",	},
{	id:	"PP-PA-002",	nombre:	"Lasaña fresca refrigerada",	categoria:	"Platos preparados",	subcategoria:	"Platos de pasta / arroz / fideos",	formato:	"racion",	},
{	id:	"PP-PA-003",	nombre:	"Paella lista para calentar",	categoria:	"Platos preparados",	subcategoria:	"Platos de pasta / arroz / fideos",	formato:	"racion",	},
{	id:	"PP-PL-001",	nombre:	"Empanada gallega de atún",	categoria:	"Platos preparados",	subcategoria:	"Platos de pescado / marino",	formato:	"racion",	},
{	id:	"PP-PL-002",	nombre:	"Makis vegetales",	categoria:	"Platos preparados",	subcategoria:	"Platos de pescado / marino",	formato:	"racion",	},
{	id:	"PP-PL-003",	nombre:	"Nigiris surtidos",	categoria:	"Platos preparados",	subcategoria:	"Platos de pescado / marino",	formato:	"racion",	},
{	id:	"PP-PL-004",	nombre:	"Sushi variado bandeja",	categoria:	"Platos preparados",	subcategoria:	"Platos de pescado / marino",	formato:	"racion",	},
{	id:	"PP-SO-001",	nombre:	"Gazpacho fresco refrigerado",	categoria:	"Platos preparados",	subcategoria:	"Sopas y cremas frías",	formato:	"1l",	},
{	id:	"PP-SO-002",	nombre:	"Salmorejo refrigerado",	categoria:	"Platos preparados",	subcategoria:	"Sopas y cremas frías",	formato:	"1l",	},
{	id:	"PP-TO-001",	nombre:	"Tortilla de patatas con cebolla",	categoria:	"Platos preparados",	subcategoria:	"Tortilas y platos de huevos preparados",	formato:	"1ud",	},
{	id:	"PP-TO-002",	nombre:	"Tortilla de patatas entera",	categoria:	"Platos preparados",	subcategoria:	"Tortilas y platos de huevos preparados",	formato:	"1ud",	},
];
