-- ============================================================================
-- AÑADIR 378 PRODUCTOS NUEVOS A productos_genericos
-- Generado: 2026-03-08 01:20:39
-- ============================================================================

BEGIN;

INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3899', 'Rollo con sabor avellana', 'Azúcar, caramelos y chocolate', 'Chocolates y bombones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3900', 'Surtido bombones Caja Roja', 'Azúcar, caramelos y chocolate', 'Chocolates y bombones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3901', 'Pastillas enciende fuegos Encendido', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3902', 'Sacapuntas doble lápiz fino y grueso', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3903', 'Vela de cumpleaños 0', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3904', 'Vela de cumpleaños 1', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3905', 'Vela de cumpleaños 2', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3906', 'Vela de cumpleaños 3', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3907', 'Vela de cumpleaños 4', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3908', 'Vela de cumpleaños 5', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3909', 'Vela de cumpleaños 6', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3910', 'Vela de cumpleaños 7', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3911', 'Vela de cumpleaños 8', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3912', 'Vela de cumpleaños 9', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3913', 'Velas de cumpleaños', 'Bazar y Varios', 'Hogar y decoración');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3914', 'Papilla cuatro frutas con avena +8 meses', 'Bebes', 'Comida infantil');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3915', 'Papilla fruta variada +4 meses', 'Bebes', 'Comida infantil');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3916', 'Papilla fruta variada +6 meses', 'Bebes', 'Comida infantil');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3917', 'Protector cama tamaño 60 x 90 cm', 'Bebes', 'Cuidado e higiene del bebé');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3918', 'Protegeslip de incontinencia pequeño', 'Bebes', 'Pañales');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3919', 'Sangría Don Simón', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3920', 'Sidra asturiana El Mayu', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3921', 'Sidra natural Polían', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3922', 'Tequila reposado Olmeca', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3923', 'Tónica', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3924', 'Tónica zero calorías Schweppes', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3925', 'Vermouth rojo Martini', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3926', 'Paleta curada lonchas Paletas Marpa', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3927', 'Paleta de cebo ibérica La Hacienda del Ibérico', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3928', 'Picadillo de variantes', 'Carnicería y Charcutería', 'Carne preparada');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3929', 'Preparado de carne picada vacuno', 'Carnicería y Charcutería', 'Carne preparada');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3930', 'Puntas de jamón curado Incarlopsa', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3931', 'Seitán Soria Natural lonchas', 'Carnicería y Charcutería', 'Carne preparada');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3932', 'Sobrasada ibérica L''Illa especialidades', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3933', 'Sobrasada selecta L''Illa especialidades', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3934', 'Solomillo de vacuno', 'Carnicería y Charcutería', 'Vacuno');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3935', 'Sticks longaniza extra', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3936', 'Surtido de ibéricos La Hacienda del ibérico', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3937', 'Taco jamón curado', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3938', 'Tacos de vacuno añojo para guisar', 'Carnicería y Charcutería', 'Vacuno');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3939', 'Taquitos de jamón Incarlopsa', 'Carnicería y Charcutería', 'Charcuteria');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3940', 'Torreznos', 'Carnicería y Charcutería', 'Carne preparada');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3941', 'Torreznos sabor barbacoa', 'Carnicería y Charcutería', 'Carne preparada');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3942', 'Trozo de vacuno para cocido', 'Carnicería y Charcutería', 'Vacuno');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3943', 'Pajaritas vegetales', 'Congelados', 'Verduras congeladas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3944', 'Spaghetti carbonara', 'Congelados', 'Platos congelados preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3945', 'Sticks vegetales', 'Congelados', 'Verduras congeladas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3946', 'Tacos de pota al ajillo', 'Congelados', 'Platos congelados preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3947', 'Tortellini carne Pagani', 'Congelados', 'Platos congelados preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3948', 'Verduras asadas', 'Congelados', 'Verduras congeladas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3949', 'Palitos de surimi', 'Conservas y Enlatados', 'Conservas de pescado y mariscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3950', 'Palmito al natural entero', 'Conservas y Enlatados', 'Verduras, legumbres y hortalizas en conserva');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3951', 'Paté de anchoa', 'Conservas y Enlatados', 'Conservas de pescado y mariscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3952', 'Paté de jamón', 'Conservas y Enlatados', 'Conservas de pescado y mariscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3953', 'Paté de lomo de atún', 'Conservas y Enlatados', 'Conservas de pescado y mariscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3954', 'Piparra', 'Conservas y Enlatados', 'Verduras, legumbres y hortalizas en conserva');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3955', 'Remolacha cocida y pelada', 'Conservas y Enlatados', 'Verduras, legumbres y hortalizas en conserva');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3956', 'Remolacha en tiras', 'Conservas y Enlatados', 'Verduras, legumbres y hortalizas en conserva');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3957', 'Rodajas de atún de aleta amarilla', 'Conservas y Enlatados', 'Conservas de pescado y mariscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3958', 'Sardinillas en escabeche', 'Conservas y Enlatados', 'Conservas de pescado y mariscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3959', 'Sopa de cocido', 'Conservas y Enlatados', 'Sopas, cremas y otros preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3960', 'Sopa de miso', 'Conservas y Enlatados', 'Sopas, cremas y otros preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3961', 'Sopa de verduras', 'Conservas y Enlatados', 'Sopas, cremas y otros preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3962', 'Sopa hortelana', 'Conservas y Enlatados', 'Sopas, cremas y otros preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3963', 'Sopa maravilla', 'Conservas y Enlatados', 'Sopas, cremas y otros preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3964', 'Sucedáneo de caviar negro Ubago Caviartic', 'Conservas y Enlatados', 'Conservas de pescado y mariscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3965', 'Yemas de espárragos', 'Conservas y Enlatados', 'Verduras, legumbres y hortalizas en conserva');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3966', 'Paleta sombras de ojos 11 verdes', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3967', 'Paleta sombras de ojos e iluminadores Nude Romance', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3968', 'Paleta sombras de ojos e iluminadores Pink Romance', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3969', 'Perfilador de cejas 02 marrón medio', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3970', 'Perfilador de cejas Long Lasting 01 claro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3971', 'Perfilador de cejas Long Lasting 03 oscuro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3972', 'Perfilador de cejas micro 01 claro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3973', 'Perfilador de cejas micro 02 oscuro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3974', 'Perfilador de labios 06 canela', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3975', 'Perfilador de labios 07 cereza', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3976', 'Perfilador de labios 08 rojo', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3977', 'Perfilador de labios Long Lasting 01 rosa nude', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3978', 'Perfilador de labios Long Lasting 06 fucsia', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3979', 'Perfilador de labios Long Lasting 07 rojo', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3980', 'Perfilador de labios Long Lasting 08 granate', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3981', 'Perfilador de labios Long Lasting 10 canela', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3982', 'Perfilador de labios Long Lasting 11 nude', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3983', 'Perfilador de labios Long Lasting 15 canela claro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3984', 'Perfilador de ojos 01 negro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3985', 'Perfilador de ojos 02 marrón', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3986', 'Perfilador de ojos Eyeliner 02 negro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3987', 'Perfilador de ojos Eyeliner waterproof negro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3988', 'Perfilador de ojos Waterproof 01 negro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3989', 'Perfilador de ojos Waterproof 06 marrón', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3990', 'Perfilador de ojos Waterproof 07 verde turquesa', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3991', 'Perfilador de ojos Waterproof 09 azul metalizado', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3992', 'Perfilador de ojos Waterproof 101 negro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3993', 'Perfilador de ojos Waterproof 105 verde', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3994', 'Perfilador de ojos Waterproof 106 marrón', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3995', 'Perfilador de ojos Waterproof 107 azul', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3996', 'Perfilador de ojos Waterproof 108 beige', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3997', 'Perfilador de ojos Waterproof 12 verde oliva', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3998', 'Perfilador de ojos Waterproof 13 gris', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-3999', 'Perfilador de ojos Waterproof 15 azul', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4000', 'Pintalabios Creamy 201 nude', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4001', 'Pintalabios Creamy 202 rosa cálido', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4002', 'Pintalabios Creamy 204 rosa pétalo', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4003', 'Pintalabios Creamy 207 ciruela', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4004', 'Pintalabios Creamy 210 rojo', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4005', 'Pintalabios Creamy 212 marrón crema', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4006', 'Pintalabios Creamy 215 malva suave', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4007', 'Pintalabios Creamy 219 marrón chocolate', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4008', 'Pintalabios Fluido Mate 02 nude rosado', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4009', 'Pinza de cejas oblicua', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4010', 'Pinza de cejas recta', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4011', 'Polvo Compacto 24H Long Lasting 03 dorado', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4012', 'Polvo Compacto 24H Long Lasting 04 dorado oscuro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4013', 'Polvo compacto perfeccionador efecto seda 100 beige claro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4014', 'Polvo compacto perfeccionador efecto seda 300 cappuccino', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4015', 'Polvo compacto Sol claro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4016', 'Polvo compacto Sol oscuro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4017', 'Polvo suelto Translúcido 01', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4018', 'Polvos de talco', 'Cuidado personal e Higiene', 'Higiene corporal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4019', 'Povidona yodada 10%', 'Cuidado personal e Higiene', 'Higiene corporal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4020', 'Prebase corrector Primer 02 tono melocotón', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4021', 'Preservativos natural Durex', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4022', 'Preservativos natural On', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4023', 'Preservativos sensitive On', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4024', 'Preservativos sensitivo suave Durex', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4025', 'Protector labial FPS 30', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4026', 'Protector solar infantil pediátrico Sun Med FPS 50+', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4027', 'Protector térmico cabello Termo Protect', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4028', 'Protectores para los oídos de espuma Moldex', 'Cuidado personal e Higiene', 'Higiene corporal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4029', 'Protegeslip Cotton flexiform Carefree regular + tanga', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4030', 'Protegeslip maxi Cotton', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4031', 'Protegeslip maxi Dry', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4032', 'Protegeslip maxi Suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4033', 'Protegeslip micro Fresh', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4034', 'Protegeslip normal Cotton', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4035', 'Protegeslip normal Dry', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4036', 'Protegeslip normal Suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4037', 'Protegeslip normal', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4038', 'Protegeslip normal plegado Suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4039', 'Protegeslip tanga Fresh', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4040', 'Protegeslip ultrafino Fresh', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4041', 'Protegeslip y compresa 2 en 1 Suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4042', 'Recambios maquinilla de afeitar Flection System 6 hojas', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4043', 'Recambios maquinilla de afeitar Precision System 3 hojas', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4044', 'Recambios maquinilla de afeitar Precision System 6 hojas', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4045', 'Recambios maquinilla depilación Body System 6 hojas', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4046', 'Recambios maquinilla depilación Wilkinson Hydro Silk 5 hojas', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4047', 'Retoca raíces instantáneo castaño caoba Magic retouch', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4048', 'Retoca raíces instantáneo castaño Magic Retouch', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4049', 'Retoca raíces instantáneo negro Magic Retouch', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4050', 'Retoca raíces instantáneo rubio Magic Retouch', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4051', 'Rizador de pestañas', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4052', 'Sérum Be Radiant 10 en 1 cabello apagado', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4053', 'Sérum de pestañas y cejas Revival cuida, nutre y fortalece transparente', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4054', 'Sérum facial Ácido Hialurónico y Ceramidas Hidrata', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4055', 'Sérum facial iluminador Anti Ox con 15% vitamina C', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4056', 'Sérum facial potenciador 12% silicio Sisbela Reafirm', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4057', 'Sérum facial reparador Micro Cápsulas', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4058', 'Sérum facial Retinol Regen Skin', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4059', 'Sérum Liss Frizz Control iluminador', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4060', 'Sérum oil Curl Perfect cabello rizado', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4061', 'Sérum Plex Repair cabello muy dañado', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4062', 'Sérum reductor instantáneo de bolsas y ojeras Sisbela Reafirm', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4063', 'Solución fisiológica', 'Cuidado personal e Higiene', 'Higiene corporal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4064', 'Solución única para lentes de contacto blandas con ácido hialurónico', 'Cuidado personal e Higiene', 'Higiene corporal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4065', 'Sombra de ojos Creamy 02 topper', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4066', 'Sombra de ojos Creamy 03 plata', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4067', 'Sombra de ojos Creamy 05 duochromo', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4068', 'Sombra de ojos Long Lasting Multi-Stick 01 iluminador', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4069', 'Sombra de ojos Long Lasting Multi-Stick 02 rose', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4070', 'Sombra de ojos Long Lasting Multi-Stick 03 rose oscuro', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4071', 'Sombra de ojos Long Lasting Multi-Stick 04 borgoña', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4072', 'Sombra de ojos Long Lasting Multi-Stick 05 champagne', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4073', 'Sombra de ojos Long Lasting Multi-Stick 07 cobre', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4074', 'Spray cabello Ondas Surfing', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4075', 'Spray oral Própolis', 'Cuidado personal e Higiene', 'Higiene bucal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4076', 'Stick de árnica Cata Pum', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4077', 'Stick para pies anti-rozaduras', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4078', 'Sticks Jalea Real y Própolis', 'Cuidado personal e Higiene', 'Higiene bucal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4079', 'Taco pulidor de uñas manos', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4080', 'Tampones mini con aplicador suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4081', 'Tampones regular 100% algodón', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4082', 'Tampones regular con aplicador suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4083', 'Tampones regular Compak con aplicador', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4084', 'Tampones regular Pearl con aplicador', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4085', 'Tampones super 100% algodón', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4086', 'Tampones super con aplicador suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4087', 'Tampones super plus 100% algodón', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4088', 'Tampones super plus con aplicador suave', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4089', 'Tampones super plus Compak con aplicador', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4090', 'Tampones super plus Pearl con aplicador', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4091', 'Tampones super Compak con aplicador', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4092', 'Tampones super Pearl con aplicador', 'Cuidado personal e Higiene', 'Higiene íntima femenina');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4093', 'Tijera uñas', 'Cuidado personal e Higiene', 'Productos de afeitado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4094', 'Tiras adhesivas protectoras Classic color beige surtidas, elásticas y transpirables', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4095', 'Tiras adhesivas protectoras de espuma acolchado protección extra', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4096', 'Tiras adhesivas protectoras infantiles surtidas, elásticas y transpirables', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4097', 'Tiras faciales limpia poros', 'Cuidado personal e Higiene', 'Higiene corporal');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4098', 'Tónico facial árbol de té y prebióticos Facial Clean', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4099', 'Tónico facial vitamina C y niacinamida Facial Clean iluminador y antioxidante', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4100', 'Tratamiento Anti Frizz todo tipo de cabello', 'Cuidado personal e Higiene', 'Cuidado del cabello');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4101', 'Tratamiento crema reductor intensivo noche', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4102', 'Tratamiento para uñas base 9 en 1 vitaminada y alisadora', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4103', 'Tratamiento para uñas endurecedor', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4104', 'Tratamiento para uñas gel brillo top coat secado rápido', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4105', 'Tratamiento para uñas y cutículas Sérum SOS', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4106', 'Venda elástica cohesiva fijación fuerte', 'Cuidado personal e Higiene', 'Cremas y protectores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4107', 'Palitos con frutos secos', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4108', 'Palomitas de maíz dulces para microondas', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4109', 'Pasas moscatel sin semillas', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4110', 'Pasas sultanas sin semillas', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4111', 'Patatinas extra crujientes', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4112', 'Petit', 'Desayuno y Snack', 'Cereales para desayuno');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4113', 'Picatostes fritos', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4114', 'Picatostes tostados', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4115', 'Piñones', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4116', 'Pipas de calabaza natural peladas', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4117', 'Pipas de girasol fritas peladas', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4118', 'Pipas girasol barbacoa', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4119', 'Pipas girasol naturales peladas', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4120', 'Semillas de chía', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4121', 'Semillas lino dorado', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4122', 'Semillas sésamo tostado', 'Desayuno y Snack', 'Frutos secos embasados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4123', 'Snack de maíz Redes sabor barbacoa', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4124', 'Súper Cuquis', 'Desayuno y Snack', 'Cereales para desayuno');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4125', 'Té Chai', 'Desayuno y Snack', 'Té e infusiones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4126', 'Té Matcha en polvo', 'Desayuno y Snack', 'Té e infusiones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4127', 'Té negro con canela', 'Desayuno y Snack', 'Té e infusiones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4128', 'Té negro', 'Desayuno y Snack', 'Té e infusiones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4129', 'Té negro PG tips', 'Desayuno y Snack', 'Té e infusiones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4130', 'Té verde', 'Desayuno y Snack', 'Té e infusiones');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4131', 'Tiras de maíz frito sabor barbacoa', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4132', 'Tortitas de maíz campestre', 'Desayuno y Snack', 'Galletas saladas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4133', 'Tortitas de maíz con sabor a jamón', 'Desayuno y Snack', 'Galletas saladas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4134', 'Tortitas de maíz', 'Desayuno y Snack', 'Galletas saladas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4135', 'Trigo snack sabor ahumado', 'Desayuno y Snack', 'Snack salados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4136', 'Pimentón dulce de la Vera', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4137', 'Pimentón dulce', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4138', 'Pimienta blanca molida', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4139', 'Pimienta negra en grano', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4140', 'Pimienta negra molida', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4141', 'Preparado en polvo gelatina cereza', 'Despensa', 'Azúcares y edulcorantes');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4142', 'Preparado en polvo gelatina frutos rojos 0% azúcares', 'Despensa', 'Azúcares y edulcorantes');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4143', 'Preparado en polvo gelatina maracuyá', 'Despensa', 'Azúcares y edulcorantes');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4144', 'Preparado en polvo instantáneo para crepes', 'Despensa', 'Salsas, caldos y condimentos preparados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4145', 'Preparado para ahumar', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4146', 'Preparado para repostería con impulsor incorporado', 'Despensa', 'Harinas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4147', 'Quinoa cocida blanca y roja Sabroz', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4148', 'Quinoa', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4149', 'Romero', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4150', 'Sazonador para burritos', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4151', 'Sazonador para fajitas sabor tex-mex', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4152', 'Sazonador para paella con azafrán', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4153', 'Sazonador Topping', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4154', 'Sémola de trigo', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4155', 'Sirope de agave', 'Despensa', 'Azúcares y edulcorantes');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4156', 'Soja texturizada Luengo', 'Despensa', 'Legumbres secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4157', 'Spaghetti Armando', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4158', 'Spaghetti fino', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4159', 'Spaghetti', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4160', 'Spaghetti integral', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4161', 'Spaghetti sin gluten Felicia', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4162', 'Tallarines', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4163', 'Tomillo', 'Despensa', 'Especias e hierbas secas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4164', 'Tubitos', 'Despensa', 'Arroz, pasta y quinoa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4165', 'Preparado de verdura para cocido', 'Frutas y Verduras', 'Verduras');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4166', 'Preparado de verduras para sofreír cortado y lavado', 'Frutas y Verduras', 'Verduras');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4167', 'Puerros', 'Frutas y Verduras', 'Verduras');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4168', 'Rabanitos', 'Frutas y Verduras', 'Verduras');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4169', 'Rúcula lavada', 'Frutas y Verduras', 'Verduras');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4170', 'Sopa de verduras cortada y lavada', 'Frutas y Verduras', 'Verduras');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4171', 'Verdura para crema de calabaza', 'Frutas y Verduras', 'Verduras');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4172', 'Pajitas rectas reutilizables', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4173', 'Palillos redondos', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4174', 'Paño seca vajillas', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4175', 'Pañuelos de papel Aloe Vera', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4176', 'Pañuelos de papel Extra Suaves', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4177', 'Pañuelos de papel Mentol', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4178', 'Papel de aluminio', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4179', 'Papel higiénico Comfort', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4180', 'Papel higiénico Doble Rollo', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4181', 'Papel higiénico húmedo WC', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4182', 'Papel higiénico Suave', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4183', 'Papel vegetal', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4184', 'Pastillas antical para lavadora', 'Hogar', 'Detergentes para ropa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4185', 'Pastillas cisterna', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4186', 'Pastillas desinfectantes multiusos', 'Hogar', 'Lejia y desinfectantes');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4187', 'Perfumador ropa intensificador de fragancia', 'Hogar', 'Suavizantes');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4188', 'Pila alcalina AA LR6', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4189', 'Pila alcalina AAA LR03', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4190', 'Pinzas de ropa', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4191', 'Planchado fácil', 'Hogar', 'Detergentes para ropa');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4192', 'Plato llano biodegradable', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4193', 'Plato postre biodegradable', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4194', 'Plumero atrapa polvo', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4195', 'Plumero de avestruz extensible', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4196', 'Posavajillas', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4197', 'Quitagrasas perfumado', 'Hogar', 'Limpiadores de superficie');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4198', 'Quitagrasas perfume Marsella', 'Hogar', 'Limpiadores de superficie');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4199', 'Quitagrasas KH-7', 'Hogar', 'Limpiadores de superficie');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4200', 'Rasqueta Vitrocerámicas', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4201', 'Raticida cebo fresco', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4202', 'Recambio antihumedad con aromas cítricos', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4203', 'Recambio mopa microfibra pequeño', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4204', 'Recambios plumero', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4205', 'Recarga jabón de manos dermoprotector', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4206', 'Recogedor antivuelco con palo', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4207', 'Reductor de pH para piscina', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4208', 'Rodillo quitapelusas', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4209', 'Saquitos antipolillas Ropa Limpia', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4210', 'Servilleta papel', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4211', 'Servilleta papel Cocktail', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4212', 'Servilleta papel suave', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4213', 'Set antihumedad con aromas cítricos', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4214', 'Sosa cáustica', 'Hogar', 'Limpiadores de superficie');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4215', 'Tenedores de plástico reutilizables', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4216', 'Trampa matacucarachas', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4217', 'Vasos grandes de plástico reutilizables', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4218', 'Vasos medianos de plástico reutilizables', 'Hogar', 'Utensilios y consumibles de limpieza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4219', 'Vela perfumada Berries', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4220', 'Vela perfumada Chai', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4221', 'Vela perfumada Crème Brûlée', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4222', 'Vela perfumada Fruta Tropical', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4223', 'Vela perfumada Matcha', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4224', 'Vela perfumada Santal Vanilla', 'Hogar', 'Ambientadores');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4225', 'Perlas Omega 3', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4226', 'Petit sabores', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4227', 'Postre de coco Natural Alpro sin azúcares añadidos', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4228', 'Postre de soja sabor vainilla', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4229', 'Postre de soja natural', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4230', 'Postre de soja sabor arándanos Alpro', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4231', 'Postre de soja sabor Natural con coco Alpro', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4232', 'Postre lácteo con arándanos +Proteínas 0% MG 10 g proteínas', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4233', 'Postre lácteo con fruta 0% MG 0% azúcares añadidos', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4234', 'Postre lácteo cremoso natural edulcorado 0% MG 0% azúcares añadidos', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4235', 'Postre lácteo natural +Proteínas 0% MG 10 g proteínas', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4236', 'Postre lácteo natural +Proteínas 0% MG 12 g proteínas', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4237', 'Postre lácteo sabor coco +Proteínas 0% MG 10 g proteínas', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4238', 'Postre lácteo sin lactosa natural 0% MG 0% azúcares añadidos', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4239', 'Preparado lácteo crecimiento +1 año', 'Lácteos y Huevos', 'Leche y bebidas "lácteas"');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4240', 'Preparado lácteo crecimiento Peques 3 Puleva', 'Lácteos y Huevos', 'Leche y bebidas "lácteas"');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4241', 'Requesón mezcla', 'Lácteos y Huevos', 'Quesos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4242', 'Tiramisú', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4243', 'Tocino de cielo', 'Lácteos y Huevos', 'Postres lácteos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4244', 'Tofu firme', 'Lácteos y Huevos', 'Grasas vegetales');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4245', 'Snack corazones perro adulto', 'Mascotas', 'Comida para perros');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4246', 'Snack gato aperitivo líquido', 'Mascotas', 'Comida para otros animales');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4247', 'Snack gato crunchy con hierba gatera cuidado de dientes', 'Mascotas', 'Comida para otros animales');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4248', 'Stick dental perro adulto con menta', 'Mascotas', 'Accesorios para perros');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4249', 'Palmeritas', 'Panadería y Pastelería', 'Bollos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4250', 'Piadina', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4251', 'Picos 100% integrales', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4252', 'Picos camperos', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4253', 'Picos', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4254', 'Picos reventaos', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4255', 'Picos sin gluten', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4256', 'Regañá artesana', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4257', 'Regañá', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4258', 'Rosquilla al cacao', 'Panadería y Pastelería', 'Bollos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4259', 'Rosquilla de cacao Caocream', 'Panadería y Pastelería', 'Bollos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4260', 'Rosquillas al cacao', 'Panadería y Pastelería', 'Bollos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4261', 'Rosquito frito con azúcar', 'Panadería y Pastelería', 'Bollos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4262', 'Sobaos', 'Panadería y Pastelería', 'Bollos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4263', 'Surtido de picos, colines y regañás con sésamo', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4264', 'Tortillas de avena 51%', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4265', 'Tortillas de maíz', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4266', 'Tortillas de trigo', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4267', 'Tortillas de trigo integrales', 'Panadería y Pastelería', 'Pan fresco');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4268', 'Trenza con nueces 4%', 'Panadería y Pastelería', 'Bollos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4269', 'Sepia Faraónica', 'Pescadería', 'Moluscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4270', 'Sepia troceada Faraónica', 'Pescadería', 'Moluscos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4271', 'Trucha Arco iris abierta a la espalda', 'Pescadería', 'Pescado');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4272', 'Surtido sushi Bento grande', 'Platos preparados', 'Platos preparados refrigerados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4273', 'Surtido sushi Bento mix', 'Platos preparados', 'Platos preparados refrigerados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4274', 'Surtido sushi Bento pequeño', 'Platos preparados', 'Platos preparados refrigerados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4275', 'Tabulé oriental', 'Platos preparados', 'Ensaladas listas');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4276', 'Tsatsiki', 'Platos preparados', 'Platos preparados refrigerados');

COMMIT;

-- Verificar
SELECT COUNT(*) FROM productos_genericos;