-- ============================================================================
-- AÑADIR 307 PRODUCTOS A productos_genericos
-- Generado: 2026-03-08 14:55:38
-- ============================================================================

BEGIN;

INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4277', 'Agua de coco 100% natural', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4278', 'Agua de colonia bebÃ© Nenuco', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4279', 'Agua de colonia Citrus Classic', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4280', 'Agua de colonia Floral Infusion', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4281', 'Agua de colonia fresca infantil con notas cÃ­tricas', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4282', 'Agua de colonia S3 Classic fresh', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4283', 'Agua de colonia S3 MediterrÃ¡nea', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4284', 'Agua de peinado cabello Aqua Styling', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4285', 'Agua de soda con sifÃ³n La Casa', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4286', 'Agua destilada', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4287', 'Agua facial de avena', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4288', 'Agua micelar cara y ojos Facial Clean', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4289', 'Agua mineral con gas grande Aguadoy', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4290', 'Agua mineral con gas grande San Pellegrino', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4291', 'Agua mineral con gas grande Vichy Catalan', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4292', 'Agua mineral con gas pequeÃ±a Aguadoy', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4293', 'Agua mineral con gas pequeÃ±a Vichy Catalan', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4294', 'Agua mineral grande Aguadoy', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4295', 'Agua mineral grande Bezoya', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4296', 'Agua mineral grande Fuente Dehesa', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4297', 'Agua mineral grande LanjarÃ³n', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4298', 'Agua mineral grande Liviana', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4299', 'Agua mineral grande NestlÃ© Aquarel', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4300', 'Agua mineral grande SolÃ¡n de Cabras', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4301', 'Agua mineral mediana Aguadoy', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4302', 'Agua mineral mediana Fuente Dehesa', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4303', 'Agua mineral pequeÃ±a Aguadoy', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4304', 'Agua mineral pequeÃ±a Aguadoy tapÃ³n infantil', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4305', 'Agua mineral pequeÃ±a Fuente Dehesa', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4306', 'Agua mineral pequeÃ±a Fuente Dehesa tapÃ³n infantil', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4307', 'Agua oxigenada desinfectante antisÃ©ptico', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4308', 'Agua para plancha perfume ropa limpia', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4309', 'Agua perfumada bebÃ© con notas florales', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4310', 'Aguacate', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4311', 'Aguacates', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4312', 'Aperitivo de patata sabor original Pringles', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4313', 'AtÃºn claro en escabeche blanco', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4314', 'AzÃºcar blanco en sobres', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4315', 'AzÃºcar blanco', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4316', 'Bebida 5 frutas sin azÃºcares aÃ±adidos', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4317', 'Bebida aromatizada a base de vino para cocinar Abuela Carola', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4318', 'Bebida Bahamas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4319', 'Bebida de arÃ¡ndanos y frutas rojas sin azÃºcares aÃ±adidos', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4320', 'Bebida de melocotÃ³n sin azÃºcares aÃ±adidos', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4321', 'Bebida de zumo de naranja, mango y zanahoria La Verja sin azÃºcares aÃ±adidos', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4322', 'Bebida energÃ©tica Energy Drink', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4323', 'Bebida energÃ©tica Energy Drink Zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4324', 'Bebida energÃ©tica energy Monster', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4325', 'Bebida energÃ©tica Energy Monster', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4326', 'Bebida energÃ©tica Energy Ultra zero Monster', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4327', 'Bebida energÃ©tica Furious Energy drink', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4328', 'Bebida energÃ©tica original Burn', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4329', 'Bebida energÃ©tica Red Bull', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4330', 'Bebida energÃ©tica Zero Berries Energy drink', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4331', 'Bebida energÃ©tica Zero Full Tropic Energy drink', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4332', 'Bebida energÃ©tica Zero Furious Energy drink', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4333', 'Bebida energÃ©tica Zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4334', 'Bebida energÃ©tica Zero Katrine Energy drink', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4335', 'Bebida espirituosa Convidado de Baco', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4336', 'Bebida Florida', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4337', 'Bebida Florida Sunny Delight', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4338', 'Bebida isotÃ³nica Iso On blue', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4339', 'Bebida isotÃ³nica limÃ³n Aquarius', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4340', 'Bebida isotÃ³nica limÃ³n Aquarius zero azÃºcar', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4341', 'Bebida isotÃ³nica naranja Aquarius', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4342', 'Bebida isotÃ³nica sabor cÃ­trico Iso drink', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4343', 'Bebida isotÃ³nica sabor cÃ­trico Iso drink zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4344', 'Bebida KÃ©fir de coco', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4345', 'Bebida KÃ©fir natural 0% MG', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4346', 'Bebida multivitaminas sin azÃºcares aÃ±adidos', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4347', 'Bebida preparada de ron sabor mojito La Recompensa Ice', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4348', 'Bebida refrescante aromatizada tinto sin alcohol light Castillo de SalobreÃ±a', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4349', 'Bebida tropical sin azÃºcares aÃ±adidos', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4350', 'Bebida zumo de manzana El Lagar sin alcohol', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4351', 'Bitter Kas sin alcohol', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4352', 'Bombones cereza al licor con chocolate negro', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4353', 'Boquerones al vinagre en aceite de girasol', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4354', 'Boquerones aliÃ±ados', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4355', 'Boquerones en vinagre en aceite de girasol', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4356', 'Brandy de Jerez solera reserva Convidado de Baco', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4357', 'Cacao soluble ColaCao original', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4358', 'CalabacÃ­n blanco', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4359', 'Carrilladas de cerdo al vino', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4360', 'Cava brut Anna CodornÃ­u', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4361', 'Cava brut CabrÃ© & SabatÃ©', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4362', 'Cava brut nature Jaume Serra', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4363', 'Cava brut nature reserva vintage CabrÃ© & SabatÃ©', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4364', 'Cava semi seco CabrÃ© & SabatÃ©', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4365', 'Cerveza 0,0% sin alcohol Falke', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4366', 'Cerveza 0,0% sin alcohol tostada Falke', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4367', 'Cerveza 0,0% sin alcohol tostada Mahou', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4368', 'Cerveza clÃ¡sica Mahou', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4369', 'Cerveza ClÃ¡sica Steinburg', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4370', 'Cerveza con aguardiente de agave Desperados', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4371', 'Cerveza Corona', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4372', 'Cerveza de trigo Paulaner', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4373', 'Cerveza doble malta 1897', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4374', 'Cerveza doble malta Voll-Damm', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4375', 'Cerveza El Ãguila sin filtrar', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4376', 'Cerveza especial Estrella Galicia', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4377', 'Cerveza especial Mahou', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4378', 'Cerveza especial San Miguel', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4379', 'Cerveza especial sin gluten Falke', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4380', 'Cerveza especial Steinburg', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4381', 'Cerveza extra 1906 reserva especial', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4382', 'Cerveza Heineken', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4383', 'Cerveza negra Ambar', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4384', 'Cerveza Radler Falke 0,0% sin alcohol', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4385', 'Cerveza Radler Steinburg con zumo natural de limÃ³n', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4386', 'Cerveza reserva 1925 Alhambra', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4387', 'Cerveza Shandy Steinburg sabor limÃ³n', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4388', 'Cerveza sin alcohol Falke', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4389', 'Cerveza sin alcohol Mahou', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4390', 'Cerveza sin gluten 0,0% sin alcohol tostada Mahou', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4391', 'Cerveza sin gluten Mahou', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4392', 'Cerveza Suave Steinburg', 'Bebidas', 'Cerveza');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4393', 'ChampiÃ±ones blancos', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4394', 'Chipirones enharinados ultracongelado', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4395', 'Chipirones rellenos enteros en aceite de girasol', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4396', 'Colorete fluido Blush mate 01 rosa amarronado', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4397', 'Crema de calzado blanco autobrillante con aplicador', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4398', 'DentÃ­frico Total original Colgate', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4399', 'Esparadrapo de papel adhesivo microporoso color blanco', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4400', 'EspÃ¡rragos blancos delgados cortos', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4401', 'EspÃ¡rragos blancos medianos', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4402', 'EspÃ¡rragos blancos muy gruesos cortos', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4403', 'EspÃ¡rragos blancos muy gruesos enteros', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4404', 'Esponja de baÃ±o dermo agua', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4405', 'Filete de salmÃ³n rosado salvaje con piel ultracongelado', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4406', 'Gel de baÃ±o Classic original Magno', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4407', 'Ginebra Dry Gin Seagram''s', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4408', 'Ginebra London Dry Gin Beefeater', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4409', 'Ginebra London Dry Gin Glivery', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4410', 'Ginebra London Dry Gin Larios', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4411', 'Ginebra London Dry Gin Tanqueray', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4412', 'Ginebra strawberry Gin Glivery', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4413', 'Ginebra sweet Gin Exotic Glivery', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4414', 'Golosinas Rega Relli rellena con zumo de fruta', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4415', 'Harina de maÃ­z blanco precocida', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4416', 'Hueso blanco de cerdo salado', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4417', 'JabÃ³n de manos en pastilla natural original Heno de Pravia', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4418', 'Laca de uÃ±as manicura francesa 01 blanco punta', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4419', 'Laca de uÃ±as manicura francesa 06 blanco milky', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4420', 'LÃ¡grimas hidratantes para los ojos con hialuronato sÃ³dico 0,2%', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4421', 'Lambrusco rosado frizzante dell''Emilia Piccolo Giovanni', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4422', 'Lavavajillas Ultra Original Fairy lÃ­quido', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4423', 'Licor de anÃ­s dulce Dama Mayor', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4424', 'Licor de anÃ­s dulce La Castellana', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4425', 'Licor de hierbas JÃ¤germeister', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4426', 'Licor de hierbas Puente Pazos', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4427', 'Licor de limoncello Franzini', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4428', 'Licor dulce Amaretto Del Patriarca', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4429', 'Licor mora sin alcohol Pi.omka', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4430', 'Macarrones Mac & Cheese Bacon gratinados', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4431', 'Mantel de papel blanco', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4432', 'Maquillaje Mate Stick multiusos bronzer 400 chocolate', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4433', 'Margarina TulipÃ¡n Original', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4434', 'Mascarilla Hydra hyaluronic cabello de normal a seco', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4435', 'Mosto tinto CasÃ³n HistÃ³rico', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4436', 'Paleta sombras de ojos 07 marrones', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4437', 'Paleta sombras de ojos 10 rosados', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4438', 'Parches para ojos de hidrogel Energizantes con cafeÃ­na y ginseng', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4439', 'Pepperoni en lonchas', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4440', 'Pipas calabaza tostadas aguasal', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4441', 'Pipas girasol tostadas gigante aguasal', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4442', 'Polvo Compacto 24H Long Lasting 02 beige rosado', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4443', 'Polvo Compacto 24H Long Lasting 05 bronceado', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4444', 'Polvo compacto perfeccionador efecto seda 200 beige rosado', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4445', 'Queso lonchas edam de vaca Holland Corona', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4446', 'Queso tierno bola edam de vaca Holland Corona', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4447', 'Queso tierno maasdam de vaca Holland Corona', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4448', 'Queso tierno tronchÃ³n mezcla', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4449', 'Queso untar original Philadelphia', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4450', 'Refresco Berry Lime sin gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4451', 'Refresco Coca-Cola', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4452', 'Refresco Coca-Cola light', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4453', 'Refresco Coca-Cola Zero azÃºcar', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4454', 'Refresco Coca-Cola Zero Zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4455', 'Refresco cola', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4456', 'Refresco cola Zero azÃºcar', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4457', 'Refresco cola Zero azÃºcar Zero cafeÃ­na', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4458', 'Refresco de limÃ³n fresh gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4459', 'Refresco de limÃ³n zero azÃºcar fresh gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4460', 'Refresco de naranja fresh gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4461', 'Refresco de naranja sin gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4462', 'Refresco de naranja zero fresh gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4463', 'Refresco de naranja Simon Life sin gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4464', 'Refresco de naranja sin gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4465', 'Refresco Fanta limÃ³n', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4466', 'Refresco Fanta limÃ³n zero azÃºcares aÃ±adidos', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4467', 'Refresco Fanta naranja', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4468', 'Refresco Fanta naranja zero azÃºcares aÃ±adidos', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4469', 'Refresco fusiÃ³n de frutas cero sin gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4470', 'Refresco lima limÃ³n fresh gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4471', 'Refresco lima limÃ³n zero azÃºcar fresh gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4472', 'Refresco lima limÃ³n Sprite', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4473', 'Refresco limÃ³n Schweppes original', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4474', 'Refresco piÃ±a-coco cero sin gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4475', 'Refresco tÃ© sabor limÃ³n Fuze Tea', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4476', 'Refresco tÃ© sabor limÃ³n', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4477', 'Refresco tÃ© sabor limÃ³n para diluir', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4478', 'Refresco tÃ© sabor limÃ³n zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4479', 'Refresco tÃ© sabor mango zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4480', 'Refresco tÃ© sabor mango y piÃ±a', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4481', 'Refresco tÃ© sabor melocotÃ³n', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4482', 'Refresco tÃ© sabor melocotÃ³n para diluir', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4483', 'Refresco tÃ© sabor melocotÃ³n zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4484', 'Refresco tÃ© verde', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4485', 'Refresco tÃ© verde sabor maracuyÃ¡ y mango zero', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4486', 'Refresco Tropical sin gas', 'Bebidas', 'Refrescos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4487', 'Rodaja de tintorera sin piel ultracongelada', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4488', 'Ron aÃ±ejo La Recompensa', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4489', 'Ron aÃ±ejo Negrita', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4490', 'Ron blanco superior La Recompensa', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4491', 'Ron dominicano aÃ±ejo Ron BarcelÃ³', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4492', 'Ron viejo La Recompensa', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4493', 'Salsa Original Ligeresa', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4494', 'Sombra de ojos Long Lasting Multi-Stick 06 bronce', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4495', 'Tinto de verano 0,0% sin alcohol limÃ³n Don SimÃ³n', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4496', 'Tinto de verano limÃ³n CasÃ³n HistÃ³rico', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4497', 'Tinto de verano limÃ³n Don SimÃ³n', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4498', 'Tinto de verano zero limÃ³n CasÃ³n HistÃ³rico', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4499', 'Tiras adhesivas protectoras de poliuretano Aqua surtidas resistentes al agua', 'Bebidas', 'Agua');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4500', 'TÃ³nica original Schweppes', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4501', 'Tortillitas de camarones ultracongeladas', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4502', 'Velote blanco Roura', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4503', 'Vermouth blanco Maronti', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4504', 'Vermouth blanco Martini', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4505', 'Vermouth rojo Maronti reserva', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4506', 'Vinagre de vino blanco', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4507', 'Vino blanco AirÃ©n Sauvignon Blanc Fidencio DO La Mancha', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4508', 'Vino blanco airÃ©n verdejo Elegido', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4509', 'Vino blanco albariÃ±o Pazo de Orantes DO RÃ­as Baixas', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4510', 'Vino blanco albariÃ±o Ponte Tamuxe DO RÃ­as Baixas', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4511', 'Vino blanco CasÃ³n HistÃ³rico', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4512', 'Vino blanco Chardonnay Atardecer DO Somontano', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4513', 'Vino blanco Chardonnay Mar de Uvas', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4514', 'Vino blanco crianza Capricho de Uva DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4515', 'Vino blanco Don SimÃ³n', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4516', 'Vino blanco Don SimÃ³n chardonnay airÃ©n', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4517', 'Vino blanco dulce Finca La Malcriada DO Valencia', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4518', 'Vino blanco El Coto DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4519', 'Vino blanco espumoso sabor melÃ³n frizzante Piccolo Giovanni', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4520', 'Vino blanco Marina Alta DO Alicante', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4521', 'Vino blanco semidulce Diamante DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4522', 'Vino blanco suave y afrutado El Pescaito', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4523', 'Vino blanco Treixadura Da Feira DO Ribeiro', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4524', 'Vino blanco verdejo AbadÃ­a MantrÃºs DO Rueda', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4525', 'Vino blanco verdejo ArribeÃ±o DO Rueda', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4526', 'Vino blanco verdejo Condado de TeÃ³n DO Rueda', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4527', 'Vino blanco verdejo frizzante DulZ.Ze', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4528', 'Vino fino Corredera DO Montilla-Moriles', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4529', 'Vino rosado Clarete Arteso DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4530', 'Vino rosado Dominio de Borgia', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4531', 'Vino rosado tempranillo syrah Fidencio DO La Mancha', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4532', 'Vino tinto 7 meses Barril NÂº7', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4533', 'Vino tinto Borsao DO Campo de Borja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4534', 'Vino tinto CasÃ³n HistÃ³rico', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4535', 'Vino tinto ColecciÃ³n de parcelas Borsao DO Campo de Borja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4536', 'Vino tinto cosecha Comportillo DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4537', 'Vino tinto cosecha Fidencio DO La Mancha', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4538', 'Vino tinto crianza AbadÃ­a MantrÃºs DO Ribera del Duero', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4539', 'Vino tinto crianza Comportillo DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4540', 'Vino tinto crianza Cune DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4541', 'Vino tinto crianza El Coto DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4542', 'Vino tinto crianza Fidencio DO La Mancha', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4543', 'Vino tinto crianza Torre Oria DO Utiel-Requena', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4544', 'Vino tinto crianza ViÃ±a Albali DO ValdepeÃ±as', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4545', 'Vino tinto Dominio de Borgia', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4546', 'Vino tinto Don SimÃ³n', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4547', 'Vino tinto dulce de aguja frizzante Rosso Dolce Cueva peccato', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4548', 'Vino tinto FariÃ±a DO Gran Dama de Toro', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4549', 'Vino tinto Merlot Mar de Uvas', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4550', 'Vino tinto Pieza Rey DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4551', 'Vino tinto reserva AbadÃ­a MantrÃºs DO Ribera del Duero', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4552', 'Vino tinto reserva Comportillo DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4553', 'Vino tinto reserva Coto de Imaz DO Rioja', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4554', 'Vino tinto roble Atardecer DO Ribera del Duero', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4555', 'Vino tinto roble FariÃ±a DO Dama de Toro', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4556', 'Vino tinto Syrah Mar de Uvas', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4557', 'Vino tinto tempranillo crianza SeÃ±orÃ­o de los Llanos DO ValdepeÃ±as', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4558', 'Vino tinto tempranillo Elegido', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4559', 'Vino tinto tempranillo Hacienda ZargÃ³n', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4560', 'Vino tinto tempranillo reserva Pata Negra DO ValdepeÃ±as', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4561', 'Vino tinto tempranillo syrah suave Caperucita tinta Torre Oria', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4562', 'Vino verde Loureiro Castelo de Moinhos DO Portugal', 'Bebidas', 'Vino');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4563', 'Vodka Knebep', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4564', 'Whisky DYC', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4565', 'Whisky escocÃ©s Ballantine''s', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4566', 'Whisky escocÃ©s Black Label Johnnie Walker', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4567', 'Whisky escocÃ©s Grand Old Parr 12 aÃ±os', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4568', 'Whisky escocÃ©s J&B', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4569', 'Whisky escocÃ©s James Webb', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4570', 'Whisky escocÃ©s Red Label Johnnie Walker', 'Bebidas', 'Licores y destilados');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4571', 'Zumo de clementina', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4572', 'Zumo de manzana', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4573', 'Zumo de manzana selecciÃ³n', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4574', 'Zumo de melocotÃ³n y uva', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4575', 'Zumo de naranja', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4576', 'Zumo de naranja reciÃ©n exprimido', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4577', 'Zumo de piÃ±a', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4578', 'Zumo de piÃ±a selecciÃ³n', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4579', 'Zumo de piÃ±a y uva', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4580', 'Zumo de tomate', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4581', 'Zumo maracuyÃ¡ y chÃ­a', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4582', 'Zumo pura naranja con pulpa', 'Bebidas', 'Zumos');
INSERT INTO productos_genericos (id_producto, nombre, categoria, subcategoria) VALUES ('ME-4583', 'Zumo pura naranja', 'Bebidas', 'Zumos');

COMMIT;