-- ============================================================================
-- AÑADIR 307 PRODUCTOS A productos_mercadona
-- Generado: 2026-03-08 14:55:38
-- Último ID: ME-4276
-- Nuevos IDs: ME-4277 a ME-4583
-- ============================================================================

BEGIN;

INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4277', 'Agua de coco Hacendado 100% natural', '2.6 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4278', 'Agua de colonia bebÃ© Nenuco', '2.85 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4279', 'Agua de colonia Deliplus Citrus Classic', '2.75 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4280', 'Agua de colonia Deliplus Floral Infusion', '2.75 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4281', 'Agua de colonia fresca infantil Deliplus con notas cÃ­tricas', '1.9 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4282', 'Agua de colonia S3 Classic fresh', '3.75 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4283', 'Agua de colonia S3 MediterrÃ¡nea', '3.75 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4284', 'Agua de peinado cabello Aqua Styling Deliplus', '2.1 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4285', 'Agua de soda con sifÃ³n La Casa', '1.6 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4286', 'Agua destilada Bosque Verde', '0.9 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4287', 'Agua facial de avena Deliplus', '2.9 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4288', 'Agua micelar cara y ojos Facial Clean', '3.0 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4289', 'Agua mineral con gas grande Aguadoy', '2.7 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4290', 'Agua mineral con gas grande San Pellegrino', '8.34 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4291', 'Agua mineral con gas grande Vichy Catalan', '1.55 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4292', 'Agua mineral con gas pequeÃ±a Aguadoy', '1.74 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4293', 'Agua mineral con gas pequeÃ±a Vichy Catalan', '6.15 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4294', 'Agua mineral grande Aguadoy', '0.95 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4295', 'Agua mineral grande Bezoya', '4.5 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4296', 'Agua mineral grande Fuente Dehesa', '1.3 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4297', 'Agua mineral grande LanjarÃ³n', '3.6 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4298', 'Agua mineral grande Liviana', '4.8 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4299', 'Agua mineral grande NestlÃ© Aquarel', '3.84 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4300', 'Agua mineral grande SolÃ¡n de Cabras', '5.34 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4301', 'Agua mineral mediana Aguadoy', '2.4 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4302', 'Agua mineral mediana Fuente Dehesa', '3.0 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4303', 'Agua mineral pequeÃ±a Aguadoy', '1.56 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4304', 'Agua mineral pequeÃ±a Aguadoy tapÃ³n infantil', '1.68 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4305', 'Agua mineral pequeÃ±a Fuente Dehesa', '1.74 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4306', 'Agua mineral pequeÃ±a Fuente Dehesa tapÃ³n infantil', '2.4 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4307', 'Agua oxigenada Deliplus desinfectante antisÃ©ptico', '0.65 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4308', 'Agua para plancha Bosque Verde perfume ropa limpia', '1.5 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4309', 'Agua perfumada bebÃ© con notas florales Deliplus', '3.2 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4310', 'Aguacate', '1.18 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4311', 'Aguacates', '3.87 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4312', 'Aperitivo de patata sabor original Pringles', '1.95 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4313', 'AtÃºn claro en escabeche blanco Hacendado', '4.7 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4314', 'AzÃºcar blanco en sobres Hacendado', '1.55 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4315', 'AzÃºcar blanco Hacendado', '1.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4316', 'Bebida 5 frutas Hacendado sin azÃºcares aÃ±adidos', '1.75 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4317', 'Bebida aromatizada a base de vino para cocinar Abuela Carola', '2.35 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4318', 'Bebida Bahamas Hacendado', '1.4 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4319', 'Bebida de arÃ¡ndanos y frutas rojas Hacendado sin azÃºcares aÃ±adidos', '1.75 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4320', 'Bebida de melocotÃ³n Hacendado sin azÃºcares aÃ±adidos', '1.0 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4321', 'Bebida de zumo de naranja, mango y zanahoria La Verja sin azÃºcares aÃ±adidos', '1.8 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4322', 'Bebida energÃ©tica Energy Drink Hacendado', '1.6 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4323', 'Bebida energÃ©tica Energy Drink Zero Hacendado', '2.4 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4324', 'Bebida energÃ©tica energy Monster', '6.68 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4325', 'Bebida energÃ©tica Energy Monster', '1.79 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4326', 'Bebida energÃ©tica Energy Ultra zero Monster', '6.68 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4327', 'Bebida energÃ©tica Furious Energy drink Hacendado', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4328', 'Bebida energÃ©tica original Burn', '3.32 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4329', 'Bebida energÃ©tica Red Bull', '7.92 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4330', 'Bebida energÃ©tica Zero Berries Energy drink', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4331', 'Bebida energÃ©tica Zero Full Tropic Energy drink', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4332', 'Bebida energÃ©tica Zero Furious Hacendado Energy drink', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4333', 'Bebida energÃ©tica Zero Hacendado', '0.4 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4334', 'Bebida energÃ©tica Zero Katrine Energy drink Hacendado', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4335', 'Bebida espirituosa Convidado de Baco', '4.3 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4336', 'Bebida Florida Hacendado', '1.4 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4337', 'Bebida Florida Sunny Delight', '1.99 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4338', 'Bebida isotÃ³nica Iso On blue Hacendado', '1.55 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4339', 'Bebida isotÃ³nica limÃ³n Aquarius', '2.1 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4340', 'Bebida isotÃ³nica limÃ³n Aquarius zero azÃºcar', '2.1 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4341', 'Bebida isotÃ³nica naranja Aquarius', '2.1 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4342', 'Bebida isotÃ³nica sabor cÃ­trico Iso drink', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4343', 'Bebida isotÃ³nica sabor cÃ­trico Iso drink zero', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4344', 'Bebida KÃ©fir de coco Hacendado', '1.1 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4345', 'Bebida KÃ©fir natural Hacendado 0% MG', '0.9 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4346', 'Bebida multivitaminas Hacendado sin azÃºcares aÃ±adidos', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4347', 'Bebida preparada de ron sabor mojito La Recompensa Ice', '1.3 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4348', 'Bebida refrescante aromatizada tinto sin alcohol light Castillo de SalobreÃ±a', '1.6 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4349', 'Bebida tropical Hacendado sin azÃºcares aÃ±adidos', '1.0 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4350', 'Bebida zumo de manzana El Lagar sin alcohol', '2.4 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4351', 'Bitter Kas sin alcohol', '7.84 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4352', 'Bombones cereza al licor Hacendado con chocolate negro', '2.2 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4353', 'Boquerones al vinagre Hacendado en aceite de girasol', '5.6 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4354', 'Boquerones aliÃ±ados Hacendado', '1.7 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4355', 'Boquerones en vinagre Hacendado en aceite de girasol', '1.65 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4356', 'Brandy de Jerez solera reserva Convidado de Baco', '6.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4357', 'Cacao soluble ColaCao original', '17.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4358', 'CalabacÃ­n blanco', '0.91 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4359', 'Carrilladas de cerdo al vino', '7.9 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4360', 'Cava brut Anna CodornÃ­u', '9.95 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4361', 'Cava brut CabrÃ© & SabatÃ©', '3.3 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4362', 'Cava brut nature Jaume Serra', '3.95 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4363', 'Cava brut nature reserva vintage CabrÃ© & SabatÃ©', '4.7 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4364', 'Cava semi seco CabrÃ© & SabatÃ©', '3.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4365', 'Cerveza 0,0% sin alcohol Falke', '2.34 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4366', 'Cerveza 0,0% sin alcohol tostada Falke', '3.68 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4367', 'Cerveza 0,0% sin alcohol tostada Mahou', '6.9 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4368', 'Cerveza clÃ¡sica Mahou', '6.96 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4369', 'Cerveza ClÃ¡sica Steinburg', '3.84 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4370', 'Cerveza con aguardiente de agave Desperados', '5.94 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4371', 'Cerveza Corona', '7.32 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4372', 'Cerveza de trigo Paulaner', '7.74 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4373', 'Cerveza doble malta 1897', '3.18 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4374', 'Cerveza doble malta Voll-Damm', '5.34 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4375', 'Cerveza El Ãguila sin filtrar', '5.1 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4376', 'Cerveza especial Estrella Galicia', '7.6 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4377', 'Cerveza especial Mahou', '8.4 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4378', 'Cerveza especial San Miguel', '6.0 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4379', 'Cerveza especial sin gluten Falke', '3.84 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4380', 'Cerveza especial Steinburg', '4.2 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4381', 'Cerveza extra 1906 reserva especial', '5.0 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4382', 'Cerveza Heineken', '5.6 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4383', 'Cerveza negra Ambar', '6.0 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4384', 'Cerveza Radler Falke 0,0% sin alcohol', '3.6 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4385', 'Cerveza Radler Steinburg con zumo natural de limÃ³n', '4.92 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4386', 'Cerveza reserva 1925 Alhambra', '7.98 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4387', 'Cerveza Shandy Steinburg sabor limÃ³n', '4.32 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4388', 'Cerveza sin alcohol Falke', '4.32 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4389', 'Cerveza sin alcohol Mahou', '7.68 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4390', 'Cerveza sin gluten 0,0% sin alcohol tostada Mahou', '6.88 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4391', 'Cerveza sin gluten Mahou', '7.14 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4392', 'Cerveza Suave Steinburg', '3.84 €', 'Bebidas', 'Cerveza', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4393', 'ChampiÃ±ones blancos', '1.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4394', 'Chipirones enharinados Hacendado ultracongelado', '4.8 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4395', 'Chipirones rellenos enteros en aceite de girasol Hacendado', '2.25 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4396', 'Colorete fluido Blush mate Deliplus 01 rosa amarronado', '5.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4397', 'Crema de calzado blanco autobrillante Bosque Verde con aplicador', '0.95 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4398', 'DentÃ­frico Total original Colgate', '2.45 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4399', 'Esparadrapo de papel adhesivo microporoso color blanco Deliplus', '1.3 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4400', 'EspÃ¡rragos blancos delgados Hacendado cortos', '1.25 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4401', 'EspÃ¡rragos blancos medianos Hacendado', '1.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4402', 'EspÃ¡rragos blancos muy gruesos Hacendado cortos', '3.1 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4403', 'EspÃ¡rragos blancos muy gruesos Hacendado enteros', '2.9 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4404', 'Esponja de baÃ±o dermo agua Deliplus', '1.5 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4405', 'Filete de salmÃ³n rosado salvaje con piel Hacendado ultracongelado', '3.88 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4406', 'Gel de baÃ±o Classic original Magno', '3.7 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4407', 'Ginebra Dry Gin Seagram''s', '17.5 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4408', 'Ginebra London Dry Gin Beefeater', '13.9 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4409', 'Ginebra London Dry Gin Glivery', '6.25 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4410', 'Ginebra London Dry Gin Larios', '10.95 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4411', 'Ginebra London Dry Gin Tanqueray', '13.95 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4412', 'Ginebra strawberry Gin Glivery', '7.15 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4413', 'Ginebra sweet Gin Exotic Glivery', '7.15 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4414', 'Golosinas Rega Relli Hacendado rellena con zumo de fruta', '1.0 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4415', 'Harina de maÃ­z blanco precocida Hacendado', '1.6 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4416', 'Hueso blanco de cerdo salado', '1.89 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4417', 'JabÃ³n de manos en pastilla natural original Heno de Pravia', '2.5 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4418', 'Laca de uÃ±as manicura francesa Deliplus 01 blanco punta', '2.75 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4419', 'Laca de uÃ±as manicura francesa Deliplus 06 blanco milky', '2.75 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4420', 'LÃ¡grimas hidratantes para los ojos Deliplus con hialuronato sÃ³dico 0,2%', '5.7 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4421', 'Lambrusco rosado frizzante dell''Emilia Piccolo Giovanni', '2.3 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4422', 'Lavavajillas Ultra Original Fairy lÃ­quido', '3.95 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4423', 'Licor de anÃ­s dulce Dama Mayor', '5.5 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4424', 'Licor de anÃ­s dulce La Castellana', '9.35 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4425', 'Licor de hierbas JÃ¤germeister', '15.25 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4426', 'Licor de hierbas Puente Pazos', '6.1 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4427', 'Licor de limoncello Franzini', '6.85 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4428', 'Licor dulce Amaretto Del Patriarca', '4.9 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4429', 'Licor mora sin alcohol Pi.omka', '3.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4430', 'Macarrones Mac & Cheese Bacon Hacendado gratinados', '2.4 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4431', 'Mantel de papel blanco Bosque Verde', '2.6 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4432', 'Maquillaje Mate Stick multiusos bronzer Deliplus 400 chocolate', '7.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4433', 'Margarina TulipÃ¡n Original', '2.95 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4434', 'Mascarilla Hydra hyaluronic Deliplus cabello de normal a seco', '2.1 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4435', 'Mosto tinto CasÃ³n HistÃ³rico', '2.1 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4436', 'Paleta sombras de ojos Deliplus 07 marrones', '4.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4437', 'Paleta sombras de ojos Deliplus 10 rosados', '4.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4438', 'Parches para ojos de hidrogel Energizantes Deliplus con cafeÃ­na y ginseng', '1.75 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4439', 'Pepperoni en lonchas Hacendado', '1.6 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4440', 'Pipas calabaza tostadas Hacendado aguasal', '1.55 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4441', 'Pipas girasol tostadas Hacendado gigante aguasal', '1.2 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4442', 'Polvo Compacto 24H Long Lasting Deliplus 02 beige rosado', '6.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4443', 'Polvo Compacto 24H Long Lasting Deliplus 05 bronceado', '6.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4444', 'Polvo compacto perfeccionador efecto seda Deliplus 200 beige rosado', '6.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4445', 'Queso lonchas edam de vaca Holland Corona', '2.1 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4446', 'Queso tierno bola edam de vaca Holland Corona', '3.9 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4447', 'Queso tierno maasdam de vaca Holland Corona', '3.5 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4448', 'Queso tierno tronchÃ³n mezcla Hacendado', '3.21 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4449', 'Queso untar original Philadelphia', '2.3 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4450', 'Refresco Berry Lime Hacendado sin gas', '1.15 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4451', 'Refresco Coca-Cola', '4.1 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4452', 'Refresco Coca-Cola light', '8.37 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4453', 'Refresco Coca-Cola Zero azÃºcar', '11.16 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4454', 'Refresco Coca-Cola Zero Zero', '11.16 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4455', 'Refresco cola Hacendado', '0.8 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4456', 'Refresco cola Hacendado Zero azÃºcar', '0.8 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4457', 'Refresco cola Hacendado Zero azÃºcar Zero cafeÃ­na', '0.8 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4458', 'Refresco de limÃ³n Hacendado fresh gas', '0.95 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4459', 'Refresco de limÃ³n Hacendado zero azÃºcar fresh gas', '0.95 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4460', 'Refresco de naranja Hacendado fresh gas', '0.95 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4461', 'Refresco de naranja Hacendado sin gas', '1.15 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4462', 'Refresco de naranja Hacendado zero fresh gas', '0.9 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4463', 'Refresco de naranja Simon Life sin gas', '1.85 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4464', 'Refresco de naranja sin gas', '1.6 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4465', 'Refresco Fanta limÃ³n', '1.85 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4466', 'Refresco Fanta limÃ³n zero azÃºcares aÃ±adidos', '4.24 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4467', 'Refresco Fanta naranja', '3.15 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4468', 'Refresco Fanta naranja zero azÃºcares aÃ±adidos', '1.85 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4469', 'Refresco fusiÃ³n de frutas Hacendado cero sin gas', '1.15 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4470', 'Refresco lima limÃ³n Hacendado fresh gas', '0.95 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4471', 'Refresco lima limÃ³n Hacendado zero azÃºcar fresh gas', '0.95 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4472', 'Refresco lima limÃ³n Sprite', '1.65 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4473', 'Refresco limÃ³n Schweppes original', '7.76 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4474', 'Refresco piÃ±a-coco Hacendado cero sin gas', '1.15 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4475', 'Refresco tÃ© sabor limÃ³n Fuze Tea', '1.99 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4476', 'Refresco tÃ© sabor limÃ³n Hacendado', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4477', 'Refresco tÃ© sabor limÃ³n Hacendado para diluir', '1.5 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4478', 'Refresco tÃ© sabor limÃ³n Hacendado zero', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4479', 'Refresco tÃ© sabor mango Hacendado zero', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4480', 'Refresco tÃ© sabor mango y piÃ±a Hacendado', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4481', 'Refresco tÃ© sabor melocotÃ³n Hacendado', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4482', 'Refresco tÃ© sabor melocotÃ³n Hacendado para diluir', '1.5 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4483', 'Refresco tÃ© sabor melocotÃ³n Hacendado zero', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4484', 'Refresco tÃ© verde Hacendado', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4485', 'Refresco tÃ© verde sabor maracuyÃ¡ y mango Hacendado zero', '1.0 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4486', 'Refresco Tropical Hacendado sin gas', '1.2 €', 'Bebidas', 'Refrescos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4487', 'Rodaja de tintorera sin piel Hacendado ultracongelada', '3.13 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4488', 'Ron aÃ±ejo La Recompensa', '6.15 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4489', 'Ron aÃ±ejo Negrita', '8.95 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4490', 'Ron blanco superior La Recompensa', '5.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4491', 'Ron dominicano aÃ±ejo Ron BarcelÃ³', '15.45 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4492', 'Ron viejo La Recompensa', '8.5 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4493', 'Salsa Original Ligeresa', '2.35 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4494', 'Sombra de ojos Long Lasting Deliplus Multi-Stick 06 bronce', '4.25 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4495', 'Tinto de verano 0,0% sin alcohol limÃ³n Don SimÃ³n', '1.55 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4496', 'Tinto de verano limÃ³n CasÃ³n HistÃ³rico', '1.3 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4497', 'Tinto de verano limÃ³n Don SimÃ³n', '1.85 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4498', 'Tinto de verano zero limÃ³n CasÃ³n HistÃ³rico', '1.15 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4499', 'Tiras adhesivas protectoras de poliuretano Aqua Deliplus surtidas resistentes al agua', '1.3 €', 'Bebidas', 'Agua', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4500', 'TÃ³nica original Schweppes', '7.84 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4501', 'Tortillitas de camarones Hacendado ultracongeladas', '2.75 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4502', 'Velote blanco Roura', '1.2 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4503', 'Vermouth blanco Maronti', '3.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4504', 'Vermouth blanco Martini', '11.9 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4505', 'Vermouth rojo Maronti reserva', '2.9 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4506', 'Vinagre de vino blanco Hacendado', '0.65 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4507', 'Vino blanco AirÃ©n Sauvignon Blanc Fidencio DO La Mancha', '1.45 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4508', 'Vino blanco airÃ©n verdejo Elegido', '2.2 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4509', 'Vino blanco albariÃ±o Pazo de Orantes DO RÃ­as Baixas', '5.7 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4510', 'Vino blanco albariÃ±o Ponte Tamuxe DO RÃ­as Baixas', '6.9 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4511', 'Vino blanco CasÃ³n HistÃ³rico', '1.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4512', 'Vino blanco Chardonnay Atardecer DO Somontano', '3.6 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4513', 'Vino blanco Chardonnay Mar de Uvas', '2.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4514', 'Vino blanco crianza Capricho de Uva DO Rioja', '6.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4515', 'Vino blanco Don SimÃ³n', '1.75 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4516', 'Vino blanco Don SimÃ³n chardonnay airÃ©n', '1.75 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4517', 'Vino blanco dulce Finca La Malcriada DO Valencia', '2.65 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4518', 'Vino blanco El Coto DO Rioja', '4.25 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4519', 'Vino blanco espumoso sabor melÃ³n frizzante Piccolo Giovanni', '2.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4520', 'Vino blanco Marina Alta DO Alicante', '4.95 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4521', 'Vino blanco semidulce Diamante DO Rioja', '4.65 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4522', 'Vino blanco suave y afrutado El Pescaito', '2.1 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4523', 'Vino blanco Treixadura Da Feira DO Ribeiro', '5.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4524', 'Vino blanco verdejo AbadÃ­a MantrÃºs DO Rueda', '2.85 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4525', 'Vino blanco verdejo ArribeÃ±o DO Rueda', '2.45 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4526', 'Vino blanco verdejo Condado de TeÃ³n DO Rueda', '3.9 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4527', 'Vino blanco verdejo frizzante DulZ.Ze', '2.8 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4528', 'Vino fino Corredera DO Montilla-Moriles', '3.25 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4529', 'Vino rosado Clarete Arteso DO Rioja', '3.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4530', 'Vino rosado Dominio de Borgia', '3.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4531', 'Vino rosado tempranillo syrah Fidencio DO La Mancha', '1.55 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4532', 'Vino tinto 7 meses Barril NÂº7', '5.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4533', 'Vino tinto Borsao DO Campo de Borja', '2.3 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4534', 'Vino tinto CasÃ³n HistÃ³rico', '1.2 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4535', 'Vino tinto ColecciÃ³n de parcelas Borsao DO Campo de Borja', '3.25 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4536', 'Vino tinto cosecha Comportillo DO Rioja', '2.9 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4537', 'Vino tinto cosecha Fidencio DO La Mancha', '1.3 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4538', 'Vino tinto crianza AbadÃ­a MantrÃºs DO Ribera del Duero', '4.5 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4539', 'Vino tinto crianza Comportillo DO Rioja', '3.45 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4540', 'Vino tinto crianza Cune DO Rioja', '7.25 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4541', 'Vino tinto crianza El Coto DO Rioja', '6.35 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4542', 'Vino tinto crianza Fidencio DO La Mancha', '1.7 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4543', 'Vino tinto crianza Torre Oria DO Utiel-Requena', '2.2 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4544', 'Vino tinto crianza ViÃ±a Albali DO ValdepeÃ±as', '2.8 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4545', 'Vino tinto Dominio de Borgia', '2.7 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4546', 'Vino tinto Don SimÃ³n', '1.75 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4547', 'Vino tinto dulce de aguja frizzante Rosso Dolce Cueva peccato', '2.6 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4548', 'Vino tinto FariÃ±a DO Gran Dama de Toro', '6.85 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4549', 'Vino tinto Merlot Mar de Uvas', '2.25 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4550', 'Vino tinto Pieza Rey DO Rioja', '9.6 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4551', 'Vino tinto reserva AbadÃ­a MantrÃºs DO Ribera del Duero', '6.3 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4552', 'Vino tinto reserva Comportillo DO Rioja', '4.65 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4553', 'Vino tinto reserva Coto de Imaz DO Rioja', '8.65 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4554', 'Vino tinto roble Atardecer DO Ribera del Duero', '4.2 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4555', 'Vino tinto roble FariÃ±a DO Dama de Toro', '3.1 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4556', 'Vino tinto Syrah Mar de Uvas', '2.15 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4557', 'Vino tinto tempranillo crianza SeÃ±orÃ­o de los Llanos DO ValdepeÃ±as', '2.0 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4558', 'Vino tinto tempranillo Elegido', '2.2 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4559', 'Vino tinto tempranillo Hacienda ZargÃ³n', '5.45 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4560', 'Vino tinto tempranillo reserva Pata Negra DO ValdepeÃ±as', '2.9 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4561', 'Vino tinto tempranillo syrah suave Caperucita tinta Torre Oria', '1.85 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4562', 'Vino verde Loureiro Castelo de Moinhos DO Portugal', '2.6 €', 'Bebidas', 'Vino', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4563', 'Vodka Knebep', '6.7 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4564', 'Whisky DYC', '10.05 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4565', 'Whisky escocÃ©s Ballantine''s', '13.25 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4566', 'Whisky escocÃ©s Black Label Johnnie Walker', '28.9 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4567', 'Whisky escocÃ©s Grand Old Parr 12 aÃ±os', '22.0 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4568', 'Whisky escocÃ©s J&B', '11.95 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4569', 'Whisky escocÃ©s James Webb', '6.15 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4570', 'Whisky escocÃ©s Red Label Johnnie Walker', '14.45 €', 'Bebidas', 'Licores y destilados', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4571', 'Zumo de clementina Hacendado', '1.8 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4572', 'Zumo de manzana Hacendado', '0.8 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4573', 'Zumo de manzana selecciÃ³n Hacendado', '1.7 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4574', 'Zumo de melocotÃ³n y uva Hacendado', '1.0 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4575', 'Zumo de naranja Hacendado', '2.1 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4576', 'Zumo de naranja reciÃ©n exprimido Hacendado', '1.95 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4577', 'Zumo de piÃ±a Hacendado', '1.75 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4578', 'Zumo de piÃ±a selecciÃ³n Hacendado', '2.6 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4579', 'Zumo de piÃ±a y uva Hacendado', '1.2 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4580', 'Zumo de tomate Hacendado', '1.05 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4581', 'Zumo maracuyÃ¡ y chÃ­a Hacendado', '1.65 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4582', 'Zumo pura naranja con pulpa Hacendado', '1.9 €', 'Bebidas', 'Zumos', '', '');
INSERT INTO productos_mercadona (id_producto, nombre, precio, categoria, subcategoria, imagen, url) VALUES ('ME-4583', 'Zumo pura naranja Hacendado', '1.85 €', 'Bebidas', 'Zumos', '', '');

COMMIT;