-- =====================================================================
-- SISTEMA DE CATEGORÍAS FIJAS - BASADO EN EXCEL
-- =====================================================================

-- PASO 1: Crear tabla de categorías (estructura fija)
CREATE TABLE IF NOT EXISTS categorias (
  id SERIAL PRIMARY KEY,
  categoria TEXT NOT NULL,
  subcategoria TEXT NOT NULL,
  UNIQUE(categoria, subcategoria)
);

-- PASO 2: Insertar las 94 categorías/subcategorías del Excel
INSERT INTO categorias (categoria, subcategoria) VALUES
  ('Bazar y Varios', 'Bombillas y material electrico'),
  ('Bazar y Varios', 'Menaje y utensilios de cocina'),
  ('Bazar y Varios', 'Otros bazar'),
  ('Bazar y Varios', 'Papelería y oficina'),
  ('Bazar y Varios', 'Pilas'),
  ('Bazar y Varios', 'Revistas'),
  ('Bebes', 'Comida infantil'),
  ('Bebes', 'Cuidado e higiene del bebé'),
  ('Bebes', 'Leche de fórmula'),
  ('Bebes', 'Pañales'),
  ('Bebes', 'Toallitas y algodón'),
  ('Bebidas', 'Agua'),
  ('Bebidas', 'Cerveza'),
  ('Bebidas', 'Licores y destilados'),
  ('Bebidas', 'Refrescos'),
  ('Bebidas', 'Vino'),
  ('Bebidas', 'Zumos'),
  ('Carnicería y Charcutería', 'Carne preparada'),
  ('Carnicería y Charcutería', 'Cerdo'),
  ('Carnicería y Charcutería', 'Charcuteria'),
  ('Carnicería y Charcutería', 'Cordero'),
  ('Carnicería y Charcutería', 'Pavo'),
  ('Carnicería y Charcutería', 'Pollo'),
  ('Carnicería y Charcutería', 'Vacuno'),
  ('Congelados', 'Helados y postres congelados'),
  ('Congelados', 'Platos congelados preparados'),
  ('Congelados', 'Verduras congeladas'),
  ('Conservas y Enlatados', 'Conservas de marisco/moluscos especificos'),
  ('Conservas y Enlatados', 'Conservas de pescado y mariscos'),
  ('Conservas y Enlatados', 'Frutas en almibar o en su jugo'),
  ('Conservas y Enlatados', 'Sopas, cremas y otros preparados'),
  ('Conservas y Enlatados', 'Verduras, legumbres y hortalizas en conserva'),
  ('Cuidado personal e Higiene', 'Cremas y protectores'),
  ('Cuidado personal e Higiene', 'Cuidado del cabello'),
  ('Cuidado personal e Higiene', 'Desodorantes'),
  ('Cuidado personal e Higiene', 'Higiene bucal'),
  ('Cuidado personal e Higiene', 'Higiene corporal'),
  ('Cuidado personal e Higiene', 'Higiene intima femenina y accesorios'),
  ('Cuidado personal e Higiene', 'Productos de afeitado'),
  ('Desayuno y Snack', 'Café y cacaos'),
  ('Desayuno y Snack', 'Cereales para desayuno'),
  ('Desayuno y Snack', 'Cremas'),
  ('Desayuno y Snack', 'Frutos secos embasados'),
  ('Desayuno y Snack', 'Galletas dulces'),
  ('Desayuno y Snack', 'Galletas saladas'),
  ('Desayuno y Snack', 'Mermelada y Miel'),
  ('Desayuno y Snack', 'Snack salados'),
  ('Desayuno y Snack', 'Té e infusiones'),
  ('Despensa', 'Aceites'),
  ('Despensa', 'Arroz, pasta y quinoa'),
  ('Despensa', 'Azúcares y edulcorantes'),
  ('Despensa', 'Especias e hierbas secas'),
  ('Despensa', 'Harinas'),
  ('Despensa', 'Legumbres secas'),
  ('Despensa', 'Sales'),
  ('Despensa', 'Salsas, caldos y condimentos preparados'),
  ('Despensa', 'Vinagres'),
  ('Frutas y Verduras', 'Fruta'),
  ('Frutas y Verduras', 'Frutos secos'),
  ('Frutas y Verduras', 'Setas'),
  ('Frutas y Verduras', 'Verduras'),
  ('Hogar', 'Ambientadores'),
  ('Hogar', 'Bolsas de basura y congelacion'),
  ('Hogar', 'Detergentes para ropa'),
  ('Hogar', 'Lavavajillas'),
  ('Hogar', 'Lejia y desinfectantes'),
  ('Hogar', 'Limpiadores de superficie'),
  ('Hogar', 'Suavizantes'),
  ('Hogar', 'Utensilios y consumibles de limpieza'),
  ('Lácteos y Huevos', 'Grasas vegetales'),
  ('Lácteos y Huevos', 'Huevos'),
  ('Lácteos y Huevos', 'Leche y bebidas "lácteas"'),
  ('Lácteos y Huevos', 'Mantequillas y Natas'),
  ('Lácteos y Huevos', 'Postres lácteos'),
  ('Lácteos y Huevos', 'Quesos'),
  ('Lácteos y Huevos', 'Yogures'),
  ('Mascotas', 'Arena y asea para gatos'),
  ('Mascotas', 'Comida para gatos'),
  ('Mascotas', 'Comida para perros'),
  ('Mascotas', 'Juguetes y accesorios'),
  ('Panadería y Pastelería', 'Bollos'),
  ('Panadería y Pastelería', 'Pan fresco'),
  ('Panadería y Pastelería', 'Pasteles y Tartas'),
  ('Panadería y Pastelería', 'Reposteria'),
  ('Pescadería', 'Marisco'),
  ('Pescadería', 'Moluscos'),
  ('Pescadería', 'Pescado'),
  ('Platos preparados', 'Bocadillos y Sándwich listos'),
  ('Platos preparados', 'Ensaladas listas'),
  ('Platos preparados', 'Platos de carne / ave'),
  ('Platos preparados', 'Platos de pasta / arroz / fideos'),
  ('Platos preparados', 'Platos de pescado / marino'),
  ('Platos preparados', 'Sopas y cremas frías'),
  ('Platos preparados', 'Tortilas y platos de huevos preparados')
ON CONFLICT DO NOTHING;

-- PASO 3: Verificar categorías insertadas
SELECT categoria, COUNT(*) as subcategorias
FROM categorias
GROUP BY categoria
ORDER BY categoria;

-- Total debe ser: 16 categorías, 94 subcategorías
